### ISSUE TITLE
Fall back to using Xpath if can't locate element by ID for source

### ISSUE THREAD

**Issue by csekamal** [appium/appium-desktop#429] opened 2018-02-27 16:27 UTC
## Appium or Appium Desktop?
Appium Desktop
## The problem
When using UiAutomator2 (desired capability automationName=UiAutomator2), appium desktop says "nteractions are not available for this element".
## Environment

- I am running Appium Desktop version _<1.3.2>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux
<img width="938" alt="appiumnotworking" src="https://user-images.githubusercontent.com/36864730/36740639-ef10dc8e-1bda-11e8-9a0a-99fe3a49c36e.PNG">

Logs:
https://gist.github.com/csekamal/88dbc3b40e61e31726119ea6dea33a1f

A portion of the log,
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8201/wd/hub/session/1eafe71b-fae6-469a-99c0-49dca522d25e/elements] with body: {"strategy":"id","selector":"btnLogin","context":"","multiple":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"1eafe71b-fae6-469a-99c0-49dca522d25e","status":0,"value":[]}
[MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/f11edb1b-34cd-46bc-9d8b-d2609c67f64c/elements 200 81 ms - 74

**Comment by dpgraham** [comment] 2018-02-28 18:37
What happens after you refresh the source?

**Comment by csekamal** [comment] 2018-02-28 18:47
Refreshed many times but same msg. Everything was working fine on android 6.0.1 before upgrade to android 7.1.1. These are the desired caps,
{
  "platformName": "Android",
  "platformVersion": "7.1.1",
  "deviceName": "SAMSUNG-SM-T377A",
  "appPackage": "com.dssinc.vha.fstt",
  "appActivity": "com.dssinc.vha.fstt.MainActivity",
  "automationName": "UiAutomator2",
  "autoGrantPermissions": "true"
}
On android 6.0.1 and A.D 1.3.2, I didn't have automationName and autoGrantPermisions caps. I had to add these two on 7.1.1 as the inspector screen hangs if not using UiAutomator2.

**Comment by dpgraham** [comment] 2018-07-03 22:08
Closing as duplicate of: https://github.com/appium/appium-desktop/issues/477

**Closed by dpgraham** 2018-07-03 22:08 UTC
Labels: P1, bug
