### ISSUE TITLE
Failed to create WDA session on 1.0.0-beta.2

### ISSUE THREAD

**Issue by gilsheps** [appium/appium-desktop#73] opened 2017-03-09 07:53 UTC
Hi,
I installed the app with dmg file on Mac with macOS Sierra.
When I am trying to run iOS, the simulator open, but there an error in the log, Failed to create WDA session - log attached.

[Failed to create WDA session.txt](https://github.com/appium/appium-desktop/files/830107/Failed.to.create.WDA.session.txt)

**Comment by imurchie** [comment] 2017-03-09 13:57
Can you add the `showXcodeLog` capability, set to `true`, and post the logs (as a link to a [gist](https://gist.github.com), not an attached text file) here?

**Comment by gilsheps** [comment] 2017-03-09 14:01
https://gist.github.com/gilsheps/2721fa7f76337e030ba782972fedd06f

**Comment by jlipps** [comment] 2017-03-15 17:13
@gilsheps i haven't seen this error before. Does it reproduce with appium on its own (i.e., not appium desktop)?

**Comment by imurchie** [comment] 2017-03-15 21:05
Me neither. Can you try to run the xcodebuild command on its own?

On the command line, run

```
cd /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=D0DFF580-BBA5-4B96-AE59-434D24539142 -configuration Debug
```

**Comment by gilsheps** [comment] 2017-03-16 08:08
@jlipps I tried with the last released version of Appium(1.6.3) there issue not reproduce.
@imurchie https://gist.github.com/gilsheps/32f1dce70ecbf2cd7b6e4841c6a1feb4. build failed, can it be that the name Appium 2.app is the issue, the space between Appium and the letter 2

**Comment by jlipps** [comment] 2017-03-16 17:01
@gilsheps yes put quotes around the path if it has spaces in it

**Comment by gilsheps** [comment] 2017-03-18 20:21
@jlipps I changed the name to Appium2.app and there still errors using the desktop app.
I did again what @imurchie suggest, xcodebuild pass.
How can I use the same version that the desktop app using?

**Comment by gilsheps** [comment] 2017-04-19 10:19
Hi,
I tested with the released version 1.0.0. The issue still reproduce. 
I updated my local server to 1.6.4 and my test run and the WebDriverAgent run.
The issue that I see the reproduce also in the Mac terminal is:
xcodebuild test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=A9B34824-6553-4DD7-AA86-AA052997C765 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent.

The command not failed when I use my local server
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=A9B34824-6553-4DD7-AA86-AA052997C765 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

Is there a way that I can test iOS?

**Comment by chennareddy08** [comment] 2017-04-23 09:10
please find attached logs for  [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.handstandapp.trainers application","sessionId":"220E5784-2B0F-4888-951A-4D93B8F42FDB","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1492938623978 (14:40:23 GMT+0530 (IST))
[logs.txt](https://github.com/appium/appium-desktop/files/949579/logs.txt)

**Comment by chennareddy08** [comment] 2017-04-23 09:15
please find attached logs for [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.handstandapp.trainers application","sessionId":"220E5784-2B0F-4888-951A-4D93B8F42FDB","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1492938623978 (14:40:23 GMT+0530 (IST))
logs.txt

https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42

**Comment by imurchie** [comment] 2017-04-25 12:28
Can you launch the app manually on the device? IT seems like it cannot run.

**Comment by chennareddy08** [comment] 2017-04-25 18:06
yes it is not launching

**Comment by imurchie** [comment] 2017-04-25 18:11
There is little that appium can do, then. Check the device logs (/Users/chennareddy/Library/Logs/CoreSimulator/DE1D852E-1D70-4D14-860F-7021DF91D347/system.log) for any information about that, and then fix the app.

**Comment by chennareddy08** [comment] 2017-04-25 18:40
please find ios logs
https://gist.github.com/chennareddy08/1404e4fa80e09daca82a495061648f42

**Comment by imurchie** [comment] 2017-04-25 18:42
```
[iOSLog] [IOS_SYSLOG_ROW] Apr 26 00:11:17 mche com.apple.CoreSimulator.SimDevice.DE1D852E-1D70-4D14-860F-7021DF91D347.launchd_sim[35135] (UIKitApplication:com.handstandapp.trainers[0x3a54][37093]): Program specified by service does not contain one of the requested architectures: 
```

You need to have a build for the simulator.

**Comment by chennareddy08** [comment] 2017-04-25 18:42
i have built using generic device

**Comment by imurchie** [comment] 2017-04-25 18:45
Build for the simulator if you are running on the simulator.

**Comment by Channareddy** [comment] 2017-04-26 09:27
Thanks @imurchie it worked for me when i built app specific version of simulator but my question is why it is not working when i built app with generic devices(Since developer usually give app built with generic device)

**Comment by imurchie** [comment] 2017-04-26 11:47
Because the generic device is not a simulator, and simulators only build for simulators. Once built for one simulator it ought to be able to run on any.

**Comment by Channareddy** [comment] 2017-04-26 12:30
got it!  Thank you  @imurchie

**Comment by gilsheps** [comment] 2017-04-26 14:59
Why you close this issue? The issue still reproduce

**Comment by jlipps** [comment] 2017-04-26 15:00
Sorry just saw recent comments and thought an issue had been silbed

**Comment by jlipps** [comment] 2017-04-26 15:00
solved

**Comment by gilsheps** [comment] 2017-06-04 08:51
@jlipps In which version you will insert the fix?
in 1.0.2-beta.2 (1.0.2-beta.2) and the issue still reproduce.

**Comment by jlipps** [comment] 2017-06-06 23:08
@gilsheps does it work when you run Appium from the command line (not Appium Desktop)?

**Comment by gilsheps** [comment] 2017-06-08 12:25
@jlipps yes, I just tried with v1.6.5

**Comment by dpgraham** [comment] 2017-10-23 05:13
@gilsheps Were you ever able to resolve this?

**Comment by gilsheps** [comment] 2017-10-23 08:15
@dpgraham yes, not sure in which version but I tested now with version 1.2.4 and the issue resolve

**Comment by dpgraham** [comment] 2017-10-23 12:57
Okay, I'll close this then. Let me know if you have any future issues.

**Closed by dpgraham** 2017-10-23 12:57 UTC
Labels: needsinfo
