### ISSUE TITLE
Fix 'element not interactable' problem by falling back to other interaction strategies

### ISSUE THREAD

**Issue by sukruk** [appium/appium-desktop#477] opened 2018-03-27 11:43 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I launched my app in inspector then open other app from deep link. When i clicked other app elements i am facing with this warning. "Interactions are not available for this element" when i see this warning i can not press button tap, set text etc. How can i solve this problem?

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2018-03-27 18:03
Does it still happen after refreshing the source?

**Comment by Omurden** [comment] 2018-06-20 13:57
Any solution for this issue?

**Comment by dpgraham** [comment] 2018-06-21 16:08
I have a plan for how to fix this but I don't know when I'll get to it.

**Comment by dpgraham** [comment] 2018-08-21 17:56
Closed as resolved.

**Closed by dpgraham** 2018-08-21 17:56 UTC
Labels: P1, bug

**Comment by MarcSteven** [comment] 2020-07-10 08:21
@dpgraham  The issue is still existing, any tips to avoid it absolutely, thank you so much.

**Comment by snehalannapure** [comment] 2020-12-10 21:46
hey @dpgraham  this issue still exists. Do you have a workaround for this. Thanks
