### ISSUE TITLE
No device found with udid *********error thrown while running the script 

### ISSUE THREAD

**Issue by Annjames1** [appium/appium-desktop#2113] opened 2022-10-04 10:02 UTC
Now am able to build WDA in xcode and we are able to create session in appium inspector
but while running the script its failing with the error -
No device found with udid d1********************

We run xcrun xctrace list devices in terminal ,and our device is getting listed but when run `idevicescreenshot` its showing
"No device found" in terminal

xcode version -14
 appium  version - 2.0.0-beta.44
 tvOS  version -15.6

**Comment by KazuCocoa** [comment] 2022-10-04 17:42
> idevicescreenshot its showing "No device found" in terminal

Then.... it seems like more OS or Xcode issue, only Apple can fix

**Comment by KazuCocoa** [comment] 2022-10-16 17:41
Duplicate of https://github.com/appium/appium-desktop/issues/2115

**Closed by KazuCocoa** 2022-10-16 17:41 UTC
