### ISSUE TITLE
Issue with appium desktop since 11/1/2020

### ISSUE THREAD

**Issue by YanivSternQA** [appium/appium-desktop#1611] opened 2020-11-03 09:43 UTC
## Appium or Appium Desktop?
 Appium Desktop
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I used to run automation testing on a daily basis but since 11/1/2020, I cannot run it anymore. 
I didn't touch my code, I didn't touch the Appium Setting. 
The error from logs:
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: Could not acquire lock on C:\Users\Yaniv\AppData\Local\Temp\uia2_device_port_guard. Original error: Error: EEXIST: file already exists, open 'C:\Users\Yaniv\AppData\Local\Temp\uia2_device_port_guard'
[debug] [35m[MJSONWP][39m     at guard (C:\Users\Yaniv\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-support\lib\util.js:477:13)
=========================================================================
Error from Appium Desktop itself:
**An unknown server-side error occurred while processing the command. Original error: Could not acquire lock on C:\Users\Yaniv\AppData\Local\Temp\uia2_device_port_guard.
 Original error: Error: EEXIST: file already exists, open 'C:\Users\Yaniv\AppData\Local\Temp\uia2_device_port_guard'**

The error from VS:
Message: 
    OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4723/wd/hub/session timed out after 60 seconds.
      ----> System.Net.WebException : The operation has timed out.
    TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

My code:
cap.AddAdditionalCapability("DeviceName", "Pixel 3a");
            cap.AddAdditionalCapability("platformName", "Android");
            cap.AddAdditionalCapability("PlatformVersion", "10.0");
            cap.AddAdditionalCapability("udid", "emulator-5554");
            cap.AddAdditionalCapability("appPackage", "com.app.marketman");
            cap.AddAdditionalCapability("appActivity", "com.app.marketman.MainActivity");
            cap.AddAdditionalCapability("ChromeOptions", "'w3c'=False");

            _driver = new AndroidDriver<IWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), cap);
            _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(30);
        

## Environment

- I am running Appium Desktop version _<Latest 4.2.1>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2020-11-03 18:49
Probably duplicate of https://github.com/appium/appium/issues/14682
1.19.0 rc or beta has the fix.
You can try out it via npm install and connect to the local appium server as https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Closed by KazuCocoa** 2020-11-03 18:49 UTC
