### ISSUE TITLE
Inspector launching to blank gray screen

### ISSUE THREAD

**Issue by iammike** [appium/appium-desktop#905] opened 2019-03-26 23:14 UTC
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

~50% of the time when starting an inspector session (hitting magnifying glass in server console) with the prebuilt release version, my screen launches to a gray rectangle.

100% of the time when doing this from my up-to-date dev fork this occurs with the attached logging in dev tools. -- I'm trying to handle some open issues, but being unable to run the inspector is a blocker. I even attempted upgrading to the latest Electron, but no luck.

[-1553641752099.log](https://github.com/appium/appium-desktop/files/3010847/-1553641752099.log)

## Environment

- I am running Appium Desktop version 1.10.0 and whatever the latest dev code is
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2019-03-26 23:15
@iammike can you open the devtools (right click the screen and `Inspect Element`) and see if there's any logs.

**Comment by dpgraham** [comment] 2019-03-26 23:16
@wswebcreation sounds like the same issue you're having is happening in 1.10.

**Comment by iammike** [comment] 2019-03-26 23:22
@dpgraham log is attached to original comment. I'm not intimately familiar with inspecting web stuff so let me know if you're looking for it in some other format.

**Comment by dpgraham** [comment] 2019-03-26 23:22
If you right click on the actual app and choose "Inspect Element" it will show Chrome Dev Tools. And then under the tab `console` it will show UI errors.

**Comment by iammike** [comment] 2019-03-26 23:27
@dpgraham Yep, that's what I had done with the above log. I realized that was with an upgraded version of Electron. Here is another with the correct version. Looks the same...

[-1553641752099.log](https://github.com/appium/appium-desktop/files/3010886/-1553641752099.log)

**Comment by dpgraham** [comment] 2019-03-26 23:43
Is this happening on 1.10.0? 

v1.10.0 shouldn't have the <CloudProviderSelector> component yet.

**Comment by iammike** [comment] 2019-03-26 23:46
I don't have logging from it occurring with 1.10.0, just anecdotal evidence that is occurs sometimes. Could just be coincidence that it's the same behavior.

**Comment by dpgraham** [comment] 2019-03-26 23:50
Probably the same error but the CloudProviderSelector error is unrelated to it.

I'll look into this more. I'm not able to reproduce this, but one of my colleagues can.

**Comment by wswebcreation** [comment] 2019-03-27 06:52
Hi @dpgraham 

This is with the latest version you send to me through Slack

[-1553669317753.log](https://github.com/appium/appium-desktop/files/3011883/-1553669317753.log)

**Comment by dpgraham** [comment] 2019-03-27 09:47
Thanks @wswebcreation... this should be enough to fix the problem.

**Comment by dpgraham** [comment] 2019-04-01 18:51
This should be fixed now. Let me know if anyone is still experiencing this.

**Closed by dpgraham** 2019-04-01 18:51 UTC
Labels: P0, bug

**Comment by DaInament** [comment] 2019-09-06 08:53
Hi, 

> This should be fixed now. Let me know if anyone is still experiencing this.

I'm expiriencing this problem.

In devTool I see this
```
/Applications/Appium.app/Contents/Resources/app/node_modules/react-dom/cjs/react-dom.development.js:506 Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in S (created by ConnectFunction)
    in ConnectFunction (created by withI18nextTranslation(Connect(S)))
    in withI18nextTranslation(Connect(S)) (created by Context.Consumer)
    in Route (created by s)
    in Switch (created by s)
    in l (created by withI18nextTranslation(l))
    in withI18nextTranslation(l) (created by s)
    in Suspense (created by s)
    in s (created by p)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by ConnectFunction)
    in ConnectFunction (created by p)
    in Provider (created by p)
    in p
    in AppContainer
```

My AppiumDesktop version 1.13.0 (1.13.0.20190505.5)
