### ISSUE TITLE
Getting error: "Call to source failed, e.replace is not a function" when trying to use appium inspector with simulator.

### ISSUE THREAD

**Issue by remcovanblarcum** [appium/appium-desktop#1245] opened 2020-02-16 13:28 UTC
I am trying to use appium for the first time.

I am not able to inspect the app on an Iphone Simulator. When I try to do so I get the error: "Call to source failed, e.replace is not a function" . My Xcode version is 11.3.1 Also tried to upgrade to beta version 11.4. but unfortunatley the same problem here.

* Appium version (or git revision) that exhibits the issue: v1.16.0-rc.2
* Desktop OS/version used to run Appium: Mac OSX 10.15.2
* Node.js version (unless using Appium.app|exe): 10.15.3
* Npm or Yarn package manager: 6.13.4
* Mobile platform/version under test: IOS 13.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: v1.15.1

I have tried to investigate the similar issues concerning this problem on this site, but none of the required solutions has worked in my case.

**Comment by remcovanblarcum** [comment] 2020-02-18 13:09
@mykola-mokhnach any updates about this issue? Today I have tried to uninstall idb. Unfortunatley the same error appears when I want to inspect my IOS.app.

**Comment by KazuCocoa** [comment] 2020-02-22 10:11
Can you show the log screen more? They may more helpful to track the error.

**Comment by remcovanblarcum** [comment] 2020-02-24 07:52
Can you please inform me where I can find the log screen you are looking for? This because I have already send you the output. My testruns are managed by IntelliJ, so the only log I can send you is the one that is created by IntelliJ.

**Comment by KazuCocoa** [comment] 2020-02-24 10:08
Ah, I thought you conducted appium embedded in Appium Desktop.

I haven't seen error `Call to source failed, e.replace is not a function` in your attached log in https://github.com/appium/appium-desktop/issues/1245#issuecomment-586713401
Do you have the full log as https://github.com/appium/appium-desktop/issues/1245#issuecomment-586706400?

Full log meant from the message of like `[Appium] Welcome to Appium v1.16.0`. We need it to track your running environment and situation. In general, the log should appear when you run appium on a console like below.

```
$ appium
[Appium] Welcome to Appium v1.15.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

I don't know how to get it in your environment (via InteliJ?) though.

**Comment by stmiller-shamrock** [comment] 2020-02-25 20:36
What I ran into with this is that the actual issue is the wrong session id. Had to go here: http://0.0.0.0:4723/wd/hub/sessions and just started trying sessions until I got the right one. So instead of trusting I got the right session id, I just check now. Seems to happen all the time in IOS but haven't run into the same issue with Android.

**Comment by KazuCocoa** [comment] 2020-02-28 16:02
hm, I could not reproduce this error for now.
It is appreciated to share the stack trace of `Call to source failed, e.replace is not a function` error to see the root source code place.

**Comment by sineqa** [comment] 2020-04-06 08:43
As others have mentioned, this error is because your session ID is invalid (perhaps it has ended?). You can easily reproduce this error by starting a session, closing it then starting another, and then using the inspector to try to attach to the first session. The server log shows the error is "invalid session id" but this error isn't parsed correctly by the UI.

However, the reason so many people, including myself, are seeing this is because when you open the inspector and go to "Attach to Session", it auto-populates the session ID in the list but often that ID is the wrong one. If it always auto-populated the most recent session ID, this issue would probably go away. Fixing the error message is only part of the problem. Happy to make a separate ticket for the other issue if there isn't one already.

Meanwhile, for those who keep hitting this. If you blank out that session ID field it will then show a dropdown - choose the bottom session in the dropdown and it will probably be your most recent one. If not, try them all one by one until it works.

**Comment by KazuCocoa** [comment] 2021-01-01 07:06
> this error is because your session ID is invalid...

I tried the above steps with the current master with attaching to an existing session (but the id was already expired.)
Probably webdriverio client behaves differently from wd.

**Closed by KazuCocoa** 2021-01-01 07:06 UTC
Labels: needsinfo
