### ISSUE TITLE
./Scripts/bootstrap.sh -d not working on Appium desktop 18 - impossible to build webDriverAgentRunner on Real Device

### ISSUE THREAD

**Issue by DvorahC** [appium/appium-desktop#1570] opened 2020-09-24 06:46 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
I need to run Appium Desktop in order to use the inspector ( to create automated UI test for iOS).
When I want to install the WebDriverAgentRunner on the real device I get the same issue all the time after running the 2 command lines below:
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d

My Error Message:
Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
Build Failed
Task failed with exit code 1:
[carthage-xcodebuild.uJMJEC.log](https://github.com/appium/appium-desktop/files/5273972/carthage-xcodebuild.uJMJEC.log)

Then I am stuck and I cannot create the WebDriverAgent on my phone.

## Environment
Xcode 12
Appium Desktop 18
Mac Os 0.15.6
iphone 7 - version iOS 14

- I am running Appium Desktop version _<18>_.
- I am on (pick one):
    - [x] Mac

I confirm that everything is fine with Appium and it is only occurring with Appium Desktop. The problem is that I need appium desktop in order to inspect the app and to build some tests.
I also read the possible solutions online but it only heps for appium...and I need Appium Desktop. 
I need to have the WebDriverAgentRunner on my iPhone.

I would really appreciate some help,
Thanks a lot
Dvorah

**Comment by KazuCocoa** [comment] 2020-09-24 09:19
Duplicate of https://github.com/appium/appium-desktop/issues/1567

**Closed by KazuCocoa** 2020-09-24 09:19 UTC

**Comment by DvorahC** [comment] 2020-09-24 09:22
> @KazuCocoa  thanks for your reply! but I am not sure it is duplicate since the solution in the #1567 is for Appium and not for Appium Desktop. I do not see any solution so far for my issue. What should I do? I opened this issue on purpose.  Let me know, thanks a lot!!

**Comment by KazuCocoa** [comment] 2020-09-24 09:35
Appium desktop accesses to appium server installed in Appium Desktop. The current issue is Xcode 12 has an issue to build some modules because of their ARM build stuff. Appium 1.18.2 has a workaround for it.
If your 'appium' meant version 1.18.2, appium works since it has the fix.

So, the current solution is to connect to Appium server outside Appium Desktop as we guide to use the latest Appium over Appium Desktop. https://github.com/appium/appium-desktop#connect-to-local-appium-server

**Comment by DvorahC** [comment] 2020-09-24 09:57
> Appium desktop accesses to appium server installed in Appium Desktop. The current issue is Xcode 12 has an issue to build some modules because of their ARM build stuff. Appium 1.18.2 has a workaround for it while Appium Desktop 1.18.0 has appium 1.18.0.
> If your 'appium' meant version 1.18.2, appium works since it has the fix.
> 
> So, the current solution is to connect to Appium server outside Appium Desktop as we guide to use the latest Appium over Appium Desktop. https://github.com/appium/appium-desktop#connect-to-local-appium-server

@KazuCocoa 
thanks! 
so Yes my Appium version is 1.18.2 and for the Desktop version I have 1.18.0 

Today I managed to use the UI this way:
1. I open my command line where my Appium WebDriverAgent is ( /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/) and I run:
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d

it works very well.

2. I run in the same place : 
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination ‘id=XXXXXXXXXXXXXXXXXXXXX' test
in order install WebDriverAgentRunner on my real device
---> works fine

3. Then I open a session from the Appium Desktop and keep all the time the Appium server running while i am playing with the UI , checking Ids or running some tests with my Java code...

This is the workaround you spoke about? Before I did not have to have the Appium server always running in the back...I could just install the webdriverAgentRunner once and play with it in the Appium Desktop.

Thanks for all the help!
I really appreciate.
Dvorah

**Comment by KazuCocoa** [comment] 2020-09-24 17:53
I meant

1) Launch an appium (1.18.2) as `$ appium` on a console
2) Launch AD and open the new session window
3) Connect to the 1) appium server from 2)'s new session window via _Custom Server_
https://github.com/appium/appium-desktop#connect-to-local-appium-server

Your java-code should send HTTP requests to the 1)

**Comment by DvorahC** [comment] 2020-09-24 18:01
> I meant
> 
> 1. Launch an appium (1.18.2) as `$ appium` on a console
> 2. Launch AD and open the new session window
> 3. Connect to the 1) appium server from 2)'s new session window via _Custom Server_
>    https://github.com/appium/appium-desktop#connect-to-local-appium-server
> 
> Your java-code should send HTTP requests to the 1)

thanks @KazuCocoa it is what I understood and what I am doing so far! This workaround works well. Thanks a lot! Dvorah
