### ISSUE TITLE
org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by chethanshetty09** [appium/appium-desktop#566] opened 2018-06-10 07:19 UTC
Appium - 1.6.1
Appium server - 1.8.0
Java-Client - 6.0.0
Selenium - 3.12.0

## The problem

I am getting java.net.SocketException: Connection reset during some step [execution]
[appium-server-logs.txt](https://github.com/appium/appium-desktop/files/2087613/appium-server-logs.txt)

Especially during the debugging the line and randomly when execution is in progress.

## Environment

MAC - 10.13.2

**Comment by syamsasi99** [comment] 2018-06-11 04:40
+1

**Comment by Chehovich** [comment] 2018-06-11 10:39
+1

**Comment by Pdubzzz** [comment] 2018-06-11 13:37
Ran into the same issue. Downgraded to Appium 5.0.4 and added dependency for latest Selenium-java client 3.12.0

**Comment by dpgraham** [comment] 2018-06-12 22:57
@chethanshetty09 can you open this ticket in https://github.com/appium/java-client

Looks like it's an issue with the Java client. And also can you provide the Java client logs in that issue. The maintainers of the java-client would probably want to see the call stack of the `java.net.SocketException`

**Comment by MoOoG** [comment] 2018-06-14 09:28
+1

**Comment by dpgraham** [comment] 2018-06-14 15:14
@syamsasi99 @Chehovich @MoOoG @Pdubzzz  Can one of you provide the Java client logs with the stacktrace? I think it's an issue with the Java client and if I get the logs I can pass them along to the team that maintains the java client and work towards a resolution.

**Comment by yakomoz** [comment] 2018-06-15 07:46
Appium - 1.8.2-beta
Java-Client - 6.0.0
Selenium - 3.12.0
macOS - 10.13.2

org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: '', ip: '', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:233)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:344)
	at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:54)
	at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:152)
	at io.appium.java_client.FindsByAccessibilityId.findElementsByAccessibilityId(FindsByAccessibilityId.java:50)
	at io.appium.java_client.AppiumDriver.findElementsByAccessibilityId(AppiumDriver.java:188)
	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:105)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:218)
	... 37 more

**Comment by chethanshetty09** [comment] 2018-06-15 10:12
@dpgraham ,

Reported under
https://github.com/appium/java-client/issues/947

**Comment by seveniruby** [comment] 2018-06-17 16:31
i found that when you add sleep time in the steps , this exception will happen, i think 
```scala
  test("test get window size"){
    val capa=new DesiredCapabilities()
    capa.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.xueqiu.android")
    capa.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".view.WelcomeActivityAlias")
    capa.setCapability(MobileCapabilityType.DEVICE_NAME, "demo")
    val driver=new AndroidDriver[WebElement](new URL("http://127.0.0.1:5723/wd/hub/"), capa)

//this code will trigger the error
    Thread.sleep(10000)

    println(driver.manage().window().getSize)
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS)
    println(driver.getPageSource)
  }
```

the bug is in the file 
https://github.com/appium/java-client/blob/v6.0.0/src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

when diff with 5.0.4
https://github.com/appium/java-client/blob/v5.0.4/src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

![image](https://user-images.githubusercontent.com/1222769/41509959-b932982c-728e-11e8-9084-72527714376a.png)

hope this will help

**Comment by yakomoz** [comment] 2018-06-18 06:47
> `System.setProperty("webdriver.http.factory", "apache")`

 did not fix it for me

**Comment by kurry3** [comment] 2018-06-19 23:50
+1

**Comment by muratme** [comment] 2018-06-21 05:50
+1

**Comment by Jules8ok** [comment] 2018-06-21 07:52
+1

**Comment by muratme** [comment] 2018-06-21 08:48
@imurchie any suggesstion about this issue?

**Comment by thulasipavankumar** [comment] 2018-06-21 09:31
+1

**Comment by dpgraham** [comment] 2018-06-21 16:06
@thulasipavankumar @muratme @kurry3 @JohnHuahuaZhan @seveniruby @yakomoz @mohitmun @syamsasi99 I'm closing this issue because it's being tracked in the java-client repository: https://github.com/appium/java-client/issues/947

**Closed by dpgraham** 2018-06-21 16:06 UTC
Labels: needsinfo

**Comment by shahnawazm786** [comment] 2022-01-06 14:01
[RemoteTestNG] detected TestNG version 7.4.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 52454
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jan 06, 2022 7:30:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jan 06, 2022 7:30:22 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 96, so returning the closest version found: 95
Jan 06, 2022 7:30:22 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 96 of 95
PASSED: createAccount

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================

Jan 06, 2022 7:30:30 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)


===============================================
Default suite
Total tests run: 1, Passes: 1, Failures: 0, Skips: 0
===============================================
