### ISSUE TITLE
[iOS]: Appium Desktop app relaunches when tried to run Inspector

### ISSUE THREAD

**Issue by ponkar** [appium/appium-desktop#176] opened 2017-05-10 06:58 UTC
## Appium or Appium Desktop?

- [ Yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The issue when we try to launc appium inspector by clicking start session, then the app is launched on device however instead inspector getting launched I see a new instance of desktop app gets launched and device crashes. This happens till the retries are maxed out

## Environment

- I am running Appium Desktop version _1.0.0
- I am on (pick one):
    - [ Sierra OS, 8gb ram] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2017-05-10 17:56
Can you provide the Appium server logs with that?

**Comment by ponkar** [comment] 2017-05-11 10:44
Please check the attached recorded video of the issue being reproduced and also you can check the logs shown there. 

[Appium_reluanch_issue.mp4.zip](https://github.com/appium/appium-desktop/files/992706/Appium_reluanch_issue.mp4.zip)


Server Log -

[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   address: 'localhost'
[Appium] Appium REST http interface listener started on localhost:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app","connectHardwareKeyboard":true,"deviceName":"iPhone 6s Plus","launchTimeout":60000,"noReset":true,"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app","connectHardwareKeyboard":true,"deviceName":"iPhone 6s Plus","launchTimeout":60000,"noReset":true,"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1494499369793 (16:12:49 GMT+0530 (IST))
[Appium] Creating new IosDriver (v1.18.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app'
[Appium]   connectHardwareKeyboard: true
[Appium]   deviceName: 'iPhone 6s Plus'
[Appium]   launchTimeout: 60000
[Appium]   noReset: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   newCommandTimeout: 0
[iOS] IosDriver version: 1.18.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: connectHardwareKeyboard.
[BaseDriver] Session created with session id: 0826417c-deab-4e36-90aa-bb23d8070104
[iOS] Xcode version set to 7.3
[iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app'
[iOS] Removing any remaining instruments sockets
[iOS] Cleaned up instruments socket /var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/instruments_sock
[iOS] Setting iOS SDK Version
[iOS] iOS SDK Version set to 9.3
[Instruments] Getting list of devices instruments supports
[Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[Instruments] Available devices: Apple TV 1080p (9.2) [5604BC23-1022-4AFF-BC09-A9127A5B915E] (Simulator),iPad 2 (9.3) [AD3AA5AE-BEED-40D3-8478-B3B0956C0149] (Simulator),iPad Air (9.3) [836E5764-F6DE-465E-ACCF-5BF366E25191] (Simulator),iPad Air 2 (9.3) [1C81F859-9FBF-4EA4-B6CE-162BE8D55E21] (Simulator),iPad Pro (9.3) [95EF6C1C-F04C-4845-ADE7-22865AF8BFF4] (Simulator),iPad Retina (9.3) [7F73EE66-ED54-4D70-AE51-7E5C7FFCD9EB] (Simulator),iPhone 4s (9.3) [89630D52-AB1A-43D8-B483-E0C67444C359] (Simulator),iPhone 5 (9.3) [1B4B44DD-9C83-47E7-8AAB-920E7107775C] (Simulator),iPhone 5s (9.3) [1DCC7884-4D6A-49F1-B127-9113240D269F] (Simulator),iPhone 6 (9.3) [BB22C0EA-9457-4159-A72A-116CD68C8B64] (Simulator),iPhone 6 Plus (9.3) [46C8B110-E543-4E2D-B71E-E43F17D30B0F] (Simulator),iPhone 6s (9.3) [AEF07234-3F3B-4463-8F3B-1F90E94A4847] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [5FED1F5F-C454-4C49-AC7F-B6D14ECB4C7E] (Simulator),iPhone 6s Plus (9.3) [AA5321E3-8FB8-407F-8DDC-BFEEC3455F42] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [DE47F4D2-8125-43D7-86E9-8A16C43A0D07] (Simulator)
[iOS] Checking whether our device string is supported
[iOSSim] Retrieving device name string for Xcode version 7.3
[iOSSim] Getting device string from options: {"deviceName":"iPhone 6s Plus","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[iOSSim] Fixing device. Changed from 'iPhone 6s Plus' to 'iPhone 6s Plus (9.3) ['
[iOSSim] Final device string is 'iPhone 6s Plus (9.3) ['
[iOS] iOS sim UDID is AA5321E3-8FB8-407F-8DDC-BFEEC3455F42
[iOSSim] Constructing iOS simulator for Xcode version 7.3 with udid 'AA5321E3-8FB8-407F-8DDC-BFEEC3455F42'
[iOS] No language specified. Using default strings
[iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Parsed app 'Localizable.strings'
[iOS] Getting bundle ID from app '/Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app': 'com.example.apple-samplecode.UICatalog'
[iOS] Extracted bundleID: com.example.apple-samplecode.UICatalog from app: /Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app
[iOS] Creating instruments
[UIAuto] Preparing bootstrap code
[UIAuto] Dynamic bootstrap dir: /Users/pavan.o/Library/Application Support/appium/bootstrap
[UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/MacOS/Appium","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/app/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
[UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
[UIAuto] Dynamic bootstrap path: /Users/pavan.o/Library/Application Support/appium/bootstrap/bootstrap-580eaff0302836d4.js
[UIAuto] Reusing dynamic bootstrap: /Users/pavan.o/Library/Application Support/appium/bootstrap/bootstrap-580eaff0302836d4.js
[iOS] User specified default device, letting instruments launch it
[iOS] Reset not set, not ending sim
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOSLog] Starting iOS 9.3 simulator log capture
[iOSLog] System log path: /Users/pavan.o/Library/Logs/CoreSimulator/AA5321E3-8FB8-407F-8DDC-BFEEC3455F42/system.log
[iOS] Not pre-launching simulator
[iOS] Starting UIAutoClient, and launching Instruments.
[UIAuto] Instruments socket server started at /var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/instruments_sock
[Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[Instruments] Attempting to run app on iPhone 6s Plus (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[Instruments] Found Insruments-Without-Delay: /Applications/Appium.app/Contents/Resources/app/node_modules/appium-instruments/thirdparty/iwd7
[Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/appium-instruments/instrumentscli0.trace -w "iPhone 6s Plus (9.3) [" /Users/pavan.o/Library/Developer/Xcode/DerivedData/UICatalog-gxqkwffjodkcswcoyvibaoppnpki/Build/Products/Debug-iphonesimulator/UICatalog.app -e UIASCRIPT "/Users/pavan.o/Library/Application Support/appium/bootstrap/bootstrap-580eaff0302836d4.js" -e UIARESULTSPATH /var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/appium-instruments'
[Instruments] And launch timeouts (in ms): {"global":60000}
[Instruments] [INST] Waiting for device to boot...
[Instruments] [INST] 2017-05-11 10:43:46 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected identifier "Wait" on line 2698 of bootstrap-580eaff0302836d4.js
[Instruments] [INST] 2017-05-11 10:43:46 +0000 Stopped: Script was stopped by the user
[Instruments] [INST STDERR] 2017-05-11 16:13:47.152 instruments[5789:363833] Attempting to change event horizon while disengage
[Instruments] [INST] Instruments Trace Complete (Duration : 40.527336s; Output : /var/folders/7x/t573_gm160jbn6k20pyb5pgmzq8mwd/T/appium-instruments/instrumentscli0.trace)
[Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments crashed on startup
[iOSSim] Killing all iOS Simulators
[iOSSim] Using fkill to kill processes: 5793

**Comment by dpgraham** [comment] 2017-05-11 17:41
Can you try this sequence of steps?

* Open Appium Desktop
* Dismiss the Update notification
* Don't do anything, and wait for a minute or two

I think the relaunch may actually be unrelated and I want to see if doing nothing relaunches the app. I think the relaunch is related to the updater dialog.

**Comment by dpgraham** [comment] 2017-05-11 17:45
Can you also double-check which version of Desktop you're using?

I don't think you're using 1.0.0, it looks like you're using a beta version.

**Comment by ponkar** [comment] 2017-05-12 09:32
I just revised it to 1.0.0 version and  also I waited after I dismissed Update notification dialog , issue still keeps reproducing
Can we sync up some time on skype to resolve this as I am in urgent to get this fixed for my project.

**Comment by ponkar** [comment] 2017-05-18 10:16
Yes this worked for me !!
in a terminal i ran appium on 4724 port , then in UI appium app started session pointing to this appium instance running on 4724 and inspector could launch properly.

This being the workaround, i think its a defect and there should not be any workaround as on windows it works in the same UI App window itself.

**Comment by dpgraham** [comment] 2017-05-18 16:24
Thanks @ponkar. I'm glad you found a workaround. Since I probably won't be able to reproduce your error, I'll close this ticket for now.

**Closed by dpgraham** 2017-05-18 16:24 UTC

**Comment by jayati0808** [comment] 2017-06-22 11:49
I am also facing the same issue and I tried the above mentioned workaround also but still appium continues to relaunch again and again.

**Comment by Mohsin-Awan7500** [comment] 2017-08-15 12:25
I'm facing the same issue. I tried many things but it still launches the app and/or web driver agent and then the app crashes. I'm using simulator.

**Comment by kababoom** [comment] 2018-03-26 09:08
Got the same issue, any news on it?
Workaround (starting appium from console) is working..

**Comment by manish9728** [comment] 2019-01-24 12:23
Not working for me. Even tried the suggestion. Please suggest
