### ISSUE TITLE
A JavaScript error occurred un the main process

### ISSUE THREAD

**Issue by EKALER-Software** [appium/appium-desktop#2025] opened 2022-04-14 04:47 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason, we require you to have tried your test case with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [*] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

A JavaScript error occurred in the main process

_Replace this section with a description of your issue_

## Environment

- I am running Appium Desktop version _<1.22.3>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2022-04-14 05:08
Possible duplicate of https://github.com/appium/appium-desktop/issues/2024
https://github.com/appium/appium-desktop#installing-on-macosv

**Closed by KazuCocoa** 2022-04-14 05:08 UTC
