### ISSUE TITLE
Appium Desktop does not load saved server presets and saved capability sets upon app restart

### ISSUE THREAD

**Issue by jgbaylon** [appium/appium-desktop#852] opened 2019-03-06 23:30 UTC
## Appium or Appium Desktop?

Appium Desktop

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop does not load saved server presets and saved capability sets upon app restart. It seems its saving them on the current app session. However, when I close and reopen the Appium Desktop, the presets and capability sets are gone.

## Environment

- I am running Appium Desktop version 1.11.0.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by myllerace** [comment] 2019-03-07 02:02
Having the same issue with 1.11.1. Also having issue with some elements not being able to click (randomly). Only noticed that after update. Going to revert

**Comment by deedora** [comment] 2019-03-07 09:23
I have a similar issue. All my Saved Capability Sets are gone after I've updated to v1.11.1 . New ones do remain saved.

**Comment by lavanyaLife360** [comment] 2019-03-07 20:39
I am having similar issue, new capability sets are also not saved.

**Comment by Apust13** [comment] 2019-03-12 13:51
Having the same issue on mac!

**Comment by tomaszmnich** [comment] 2019-03-14 09:08
Same issue on Mac with v1.11.1. Saved capability sets list is empty.

**Comment by caunem** [comment] 2019-03-14 12:29
Same here. Version 1.11.0 (1.11.0) Saved Capability Sets from previous versions disappeared after closing and reopening the app a few times.

**Comment by Carlos-Cuesta** [comment] 2019-03-22 09:35
Same problem here on Mac with v1.11.1

**Comment by dpgraham** [comment] 2019-03-22 21:54
I can't reproduce this on my side, but I can help out if people can help me find the settings file: https://github.com/nathanbuchar/electron-settings/wiki/FAQs

Can people look at their settings files (for Mac it's /Users/danielgraham/Library/Application Support/appium-desktop/Settings) and see what the contents are?

This `Settings` file saves the capability sets and I'd like to know if this is being cleared, or if it's just not being loaded properly.

**Comment by ervuks** [comment] 2019-03-25 12:58
I tried multiple times and looks like `Settings` file is being cleared. I cannot reproduce it to be 100% sure, but I had saved capabilities and `Settings` file looked like this: 
```
{"presets":{},"SAVED_SESSIONS":[],"SESSION_SERVER_PARAMS":{"local":{"port":4800,"hostname":"localhost"},"remote":{},"sauce":{},"testobject":{"dataCenter":"US"},"headspin":{},"browserstack":{},"advanced":{},"bitbar":{},"kobiton":{},"perfecto":{}},"SESSION_SERVER_TYPE":"local","SAVED_FRAMEWORK":"java","Providers":{"headspin":{"visible":true},"bitbar":{"visible":true},"kobiton":{"visible":true},"perfecto":{"visible":true},"saucelabs":{"visible":true},"testobject":{"visible":true},"browserstack":{"visible":true}},"SENTRY_PERMISSION_ALLOWED":false,"SERVER_ARGS":{"address":"0.0.0.0","allowCors":false,"automationTraceTemplatePath":null,"backendRetries":3,"bootstrapPort":4724,"callbackAddress":null,"callbackPort":null,"chromeDriverPort":null,"chromedriverExecutable":null,"debugLogSpacing":false,"defaultDevice":false,"enforceStrictCaps":false,"forceIpad":false,"forceIphone":false,"heapdumpEnabled":false,"instrumentsPath":null,"ipa":null,"isolateSimDevice":false,"launch":false,"localTimezone":false,"logFile":null,"logNoColors":false,"logTimestamp":false,"loglevel":"info","longStacktrace":false,"noPermsCheck":false,"nodeconfig":null,"port":4800,"reboot":false,"relaxedSecurityEnabled":false,"robotAddress":"0.0.0.0","robotPort":-1,"safari":false,"selendroidPort":8080,"sessionOverride":false,"shell":null,"showConfig":false,"suppressKillServer":false,"tmpDir":null,"traceDir":null,"wdaLocalPort":8100,"webhook":null,"webkitDebugProxyPort":27753,"throwInsteadOfExit":true}}
```

**Comment by dpgraham** [comment] 2019-03-25 15:46
Thank you @ervuks 

I'm very sorry for this bug everyone. This is probably a major inconvenience for many of you, and this will be my number one priority to fix this.

In the meantime, I've unpublished 1.11.0 and will publish 1.11.1 (or 1.12.0) with a fix.

**Comment by panekoreve** [comment] 2019-04-01 13:20
Hello, same issue for me, but Library/Application\ Support/appium-desktop/Settings is not empty:
[Settings.txt](https://github.com/appium/appium-desktop/files/3029553/Settings.txt)

**Comment by dpgraham** [comment] 2019-04-01 18:53
This should be fixed. Let me know if this still happens.

**Closed by dpgraham** 2019-04-01 18:53 UTC
Labels: P0, bug

**Comment by ashokkumarg** [comment] 2022-06-08 21:08
Same issue I face in Version 1.21.0

**Comment by manupou** [comment] 2022-07-18 11:33
I am facing same issue in Version 1.21.0

**Comment by jlipps** [comment] 2022-07-25 22:32
This issue is closed and the inspector is not a part of this repo anymore. Please read the README to find out where the inspector is being developed now.
