### ISSUE TITLE
Can't open latest Appium desktop release on OS Catalina

### ISSUE THREAD

**Issue by tking16** [appium/appium-desktop#1663] opened 2021-01-07 09:45 UTC
Mac version: 10.15.7
Version I'm trying to open: Appium v1.19.1
<img width="426" alt="Screenshot 2021-01-07 at 09 43 22" src="https://user-images.githubusercontent.com/13576824/103877468-0c4fb480-50cd-11eb-9924-bc2da8b57365.png">

v.17 worked fine

**Comment by KazuCocoa** [comment] 2021-01-07 20:11
Duplicate of https://github.com/appium/appium-desktop/issues/1217

**Closed by KazuCocoa** 2021-01-07 20:11 UTC
