### ISSUE TITLE
The arrow for moving left/right doesn't always show up in App Source section

### ISSUE THREAD

**Issue by deedora** [appium/appium-desktop#377] opened 2018-01-05 13:10 UTC
## The problem
The arrow for moving left/right doesn't always show up in App Source section. I think it doesn't show up when I click on the element that is very far down in a tree.

## Environment
I am running Appium Desktop version 1.2.7
I am on Mac

**Comment by dpgraham** [comment] 2018-01-10 21:31
Have you narrowed it down to when exactly that error happens?

**Comment by deedora** [comment] 2018-01-11 13:31
It happens when I click on the element in Inspector, App Source section then expands but there are no arrows. It happens when width of the expanded content is wider than App Source width. Here is the picture https://i.imgur.com/8DOVP8n.png

**Comment by dpgraham** [comment] 2018-08-21 17:55
Closed as fixed

**Comment by deedora** [comment] 2018-10-24 09:10
@dpgraham I am using Version 1.7.1 and it is not fixed. Now I can't get arrows even with resizing the window.

**Comment by dpgraham** [comment] 2018-10-24 23:56
@deedora Do you have reproduction steps for this? I can't reproduce it on my side.

**Comment by deedora** [comment] 2018-10-25 11:10
I'm not sure what I was doing but there were no arrows. I'll let you know if I figure it out.

**Comment by dpgraham** [comment] 2018-12-19 19:09
If you figure out how to reproduce, re-open this issue, and I'll have a look.

**Closed by dpgraham** 2018-12-19 19:09 UTC
Labels: P1, bug, needsinfo
