### ISSUE TITLE
The app launches and directly gets closed.

### ISSUE THREAD

**Issue by anamgangwar** [appium/appium-desktop#1268] opened 2020-03-11 09:50 UTC
## Appium or Appium Desktop?

-I have verified that my issue  occurs on both Appium and Appium Desktop
## The problem
The app launches and directly gets closed.

## Environment
- I am running Appium Desktop version _1.15.1.
xcode-select version 2354.
- I am on (pick one):
    - Mac

Running tests on real iOS device.

Appium Logs:
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"com.*****.****IN","automationName":"XCUITest","deviceName":"iPhone 8","platformName":"iOS","platformVersion":"13.3","udid":"<valid udid number>","useNewWDA":"true","xcodeOrgId":"<valid xcode Org>","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.*****.****IN","automationName":"XCUITest","deviceName":"iPhone 8","platformName":"iOS","platformVersion":"13.3","udid":"<valid udid number>","useNewWDA":"true","xcodeOrgId":"<valid xcode Org>","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1583919053560 (15:00:53 GMT+0530 (IST))
[Appium] Appium v1.15.1 creating new XCUITestDriver (v2.133.1) session
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "<valid code package>",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "deviceName": "iPhone 8",
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "13.3",
[BaseDriver]   "udid": "<valid udid number>",
[BaseDriver]   "useNewWDA": "true",
[BaseDriver]   "xcodeOrgId": "<valid xcode Org>",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Capability 'useNewWDA' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 0b6d7891-ffa4-4e95-b948-06ee9712827b
[XCUITest] Current user: 'gangwara'
[XCUITest] Available devices: <valid udid number>
[XCUITest] Creating iDevice object with udid '<valid udid number>'
[XCUITest] Determining device to run tests on: udid: '<valid udid number>', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1583919056283 (15:00:56 GMT+0530 (IST))
[XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[BaseDriver] Event 'appConfigured' logged at 1583919056284 (15:00:56 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1583919056284 (15:00:56 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1583919056285 (15:00:56 GMT+0530 (IST))
[BaseDriver] Event 'logCaptureStarted' logged at 1583919056552 (15:00:56 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium 3.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Using WDA agent: '/Applications/Appium 3.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device <valid udid number> on local port 8100, device port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Port #8100 is busy
[DevCon Factory] Successfully requested the connection for <valid udid number>:8100
[XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[XCUITest] Capability 'useNewWDA' set to true, so uninstalling WDA before proceeding
[XCUITest] Shutting down sub-processes
[XCUITest] No WDAs on the device.
[BaseDriver] Event 'wdaUninstalled' logged at 1583919057207 (15:00:57 GMT+0530 (IST))
[XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1583919057208 (15:00:57 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Dependencies up-to-date
[XCUITest] Killing running processes 'xcodebuild.*<valid udid number>' for the device <valid udid number>...
[XCUITest] 'pgrep -ifn xcodebuild.*<valid udid number>' didn't detect any matching processes. Return code: 1
[XCUITest] Generating xcode config file for orgId '<valid xcode Org>' and signingId 'iPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/y9/yn6nqr2505d5nwb94_813tmxs7tmtp/T/2020211-23479-15ufcl8.ov48/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/y9/yn6nqr2505d5nwb94_813tmxs7tmtp/T/2020211-23479-15ufcl8.ov48/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium 3.app/Contents/Resources/app/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<valid udid number> IPHONEOS_DEPLOYMENT_TARGET=13.3 -xcconfig /var/folders/y9/yn6nqr2505d5nwb94_813tmxs7tmtp/T/2020211-23479-15ufcl8.ov48/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Applications/Appium 3.app/Contents/Resources/app/node_modules/appium-webdriveragent'
[XCUITest] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[XCUITest] Log file for xcodebuild test: /Users/gangwara/Library/Developer/Xcode/DerivedData/WebDriverAgent-dggpdkjloekqvsckpynrghyhrmdn/Logs/Test/Test-WebDriverAgentRunner-1941.12.21_15-01-03-+0530.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-559E1F25-E017-47F6-B326-D1E2623A1A49/WebDriverAgentRunner-54AE7CE3-B82D-4AD7-AF45-FC5E3EB416D1/Session-WebDriverAgentRunner-1941-12-21_150104-2j7EHh.log
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[iProxy@8aa5d...] Connection was refused to port 8100
[WD Proxy] Got an unexpected response with status undefined: {"code":"ECONNRESET"}
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got response with status 200: {
[WD Proxy]   "value" : {
[WD Proxy]     "message" : "WebDriverAgent is ready to accept commands",
[WD Proxy]     "state" : "success",
[WD Proxy]     "os" : {
[WD Proxy]       "name" : "iOS",
[WD Proxy]       "version" : "13.3.1",
[WD Proxy]       "sdkVersion" : "13.0"
[WD Proxy]     },
[WD Proxy]     "ios" : {
[WD Proxy]       "simulatorVersion" : "13.3.1",
[WD Proxy]       "ip" : "10.127.*.***"
[WD Proxy]     },
[WD Proxy]     "ready" : true,
[WD Proxy]     "build" : {
[WD Proxy]       "upgradedAt" : "1583913681831",
[WD Proxy]       "time" : "Mar 11 2020 13:33:48",
[WD Proxy]       "productBundleIdentifier" : "com.facebook.WebDriverAgentRunner"
[WD Proxy]     }
[WD Proxy]   },
[WD Proxy]   "sessionId" : "8A36B8E8-6266-4952-AABB-9B52D7CDC4C1"
[WD Proxy] }
[XCUITest] WebDriverAgent information:
[XCUITest] {
[XCUITest]   "message": "WebDriverAgent is ready to accept commands",
[XCUITest]   "state": "success",
[XCUITest]   "os": {
[XCUITest]     "name": "iOS",
[XCUITest]     "version": "13.3.1",
[XCUITest]     "sdkVersion": "13.0"
[XCUITest]   },
[XCUITest]   "ios": {
[XCUITest]     "simulatorVersion": "13.3.1",
[XCUITest]     "ip": "10.127.4.***"
[XCUITest]   },
[XCUITest]   "ready": true,
[XCUITest]   "build": {
[XCUITest]     "upgradedAt": "1583913681831",
[XCUITest]     "time": "Mar 11 2020 13:33:48",
[XCUITest]     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[XCUITest]   }
[XCUITest] }
[XCUITest] WebDriverAgent successfully started after 16415ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1583919073698 (15:01:13 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[WD Proxy] Matched '/session' to command name 'createSession'
[WD Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"<valid code package>","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}

**Comment by KazuCocoa** [comment] 2020-03-12 16:19
It looks the log is not full. Could you attach the full version as GIST?
With `showIOSLog` and `showXcodeLog` may help to track the cause more.

I guess the app under test has an issue when it launches by XCTest framework.

**Comment by anamgangwar** [comment] 2020-03-13 07:36
I tried several suggestions posted.

Now facing a different issue:
[debug] [MJSONWP] 2020-03-13 13:05:28.179 xcodebuild[9677:55053] [MT] IDETestOperationsObserverDebug: (E0D7244F-5AD4-4B7A-B35F-5765081889DE) Finished requesting crash reports. Continuing with testing.
[debug] [MJSONWP] 2020-03-13 13:05:43.342519+0530 WebDriverAgentRunner-Runner[369:12092] Running tests...
[debug] [MJSONWP] 2020-03-13 13:05:43.362974+0530 WebDriverAgentRunner-Runner[369:12092] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
[debug] [MJSONWP] 2020-03-13 13:05:43.363034+0530 WebDriverAgentRunner-Runner[369:12092] (dlopen_preflight(/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[debug] [MJSONWP]   Referenced from: /private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
[debug] [MJSONWP]   Reason: no suitable image found.  Did find:
[debug] [MJSONWP] 	/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: code signature invalid for '/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[debug] [MJSONWP] 	/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: code signature invalid for '/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[debug] [MJSONWP] )
[debug] [MJSONWP] *** If you believe this error represents a bug, please attach the result bundle at /Users/gangwara/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-1941.12.23_13-05-27-+0530.xcresult
[debug] [MJSONWP] 2020-03-13 13:05:43.339 xcodebuild[9677:55053] [MT] IDETestOperationsObserverDebug: 15.307 elapsed -- Testing started completed.
[debug] [MJSONWP] 2020-03-13 13:05:43.340 xcodebuild[9677:55053] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[debug] [MJSONWP] 2020-03-13 13:05:43.340 xcodebuild[9677:55053] [MT] IDETestOperationsObserverDebug: 15.307 sec, +15.307 sec -- end
[debug] [MJSONWP] Test session results, code coverage, and logs:
[debug] [MJSONWP] 	/Users/gangwara/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaejbhejflmruhkhsmeebmhbaia/Logs/Test/Test-WebDriverAgentRunner-1941.12.23_13-05-27-+0530.xcresult
[debug] [MJSONWP] Testing failed:
[debug] [MJSONWP] 	WebDriverAgentRunner:
[debug] [MJSONWP] 		WebDriverAgentRunner-Runner.app (369) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. dlopen_preflight(/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[debug] [MJSONWP]   Referenced from: /private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
[debug] [MJSONWP]   Reason: no suitable image found.  Did find:
[debug] [MJSONWP] 	/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: code signature invalid for '/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[debug] [MJSONWP] 	/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: code signature invalid for '/private/var/containers/Bundle/Application/D4662A05-EADB-42E1-B4C9-6DC58FBDB05D/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
[debug] [MJSONWP] ))
[debug] [MJSONWP] ** TEST EXECUTE FAILED **
[debug] [MJSONWP] Testing started on 'iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [MJSONWP]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:519:15)
[debug] [MJSONWP]     at runMicrotasks (<anonymous>)
[debug] [MJSONWP]     at runNextTicks (internal/process/task_queues.js:62:5)
[debug] [MJSONWP]     at processImmediate (internal/timers.js:429:9)
[debug] [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:549:11
[debug] [MJSONWP]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[debug] [MJSONWP]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[debug] [MJSONWP]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[debug] [MJSONWP]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:529:7
[HTTP] <-- POST /wd/hub/session 500 42969 ms - 8798
[HTTP]

**Comment by KazuCocoa** [comment] 2020-03-13 16:36
Could see word, `code signature invalid for`, in some places.
What version of Xcode did you use?
Possible duplicate of https://github.com/appium/appium/issues/13927 . If so, Xcode 11.4 beta may help.

**Closed** 2020-06-02 16:18 UTC
Labels: needsinfo
