### ISSUE TITLE
appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk read only

### ISSUE THREAD

**Issue by TheCodeSharman** [appium/appium-desktop#1012] opened 2019-06-20 13:24 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

I'm getting this error with Appium Desktop version 1.13.0 using the AppImage on Ubuntu 18.04.2.

 The application at '/tmp/.mount_AppiumiE6EwI/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' is not writeable. Please grant write permissions to this file or to its parent folder 

Then I tried:
$ sudo chmod o+x /tmp/.mount_AppiumiE6EwI/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
chmod: cannot access '/tmp/.mount_AppiumiE6EwI/resources/app/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk': Permission denied

The permissions should be set correctly in the AppImage file by default anyway.

## Environment

- I am running Appium Desktop version 1.13.0
- I am on (pick one):
    - [] Mac
    - [ ] Windows
    - [x] Linux

Note that I have I older version of appium install globally - not sure if this matters:
npm list -g --depth 0 | grep appium 
├── appium@1.11.1
├── appium-doctor@1.9.0

**Comment by TheCodeSharman** [comment] 2019-06-20 13:36
Just realised that you can't have writable files inside an AppImage - this is still a bug however since I can't use an Appium server launched via Appium Desktop GUI. I'm not sure why the APK needs to be signed since I don't have deep enough knowledge of what's going on underneath. Perhaps the APK can be signed before distribution. Or else have the file copied into the user home directory, then signed.

**Comment by Julioevm** [comment] 2019-07-09 11:32
I have the same problem with 3.14, I have to use 3.10 for now which doesn't seem to have this problem.

**Comment by AndrewElfimov** [comment] 2019-07-11 13:58
Appium 1.14.0 
ubuntu 18.04 
Have the same problem

**Comment by CamiladeJesus** [comment] 2019-08-21 14:37
Same here, Appium 1.13 Ubuntu 16.04 working 
Even if I change the AppImage or UIAutomator2 permissions to read and write, it doesn't work

**Comment by veeru273** [comment] 2019-11-01 06:05
any solution w.r.t above issue ? i'm hitting the same with Appium 1.14.2 version and MAC OS Mojave 10.14.6

**Comment by KazuCocoa** [comment] 2020-12-24 09:57
Duplicate of https://github.com/appium/appium-desktop/issues/970

**Closed by KazuCocoa** 2020-12-24 09:57 UTC
Labels: help wanted
