### ISSUE TITLE
ERROR in ./main.js

### ISSUE THREAD

**Issue by gilsheps** [appium/appium-desktop#19] opened 2017-01-11 18:58 UTC
I pulled master today, and I got an error:
ERROR in ./main.js from UglifyJs
SyntaxError: Unexpected token punc «}», expected punc «:» [./~/electron-debug/index.js:23,32]

The script that I use:
npm run build
[untitled.txt](https://github.com/appium/appium-desktop/files/699782/untitled.txt)
 

And duo to this issue

 npm start is not working
[npm-debug.txt](https://github.com/appium/appium-desktop/files/699794/npm-debug.txt)

**Comment by jlipps** [comment] 2017-01-19 21:53
@gilsheps after you pulled master, did you `rm -rf node_modules && npm install` before you ran the build? And what happens if you run `npm run dev` which is the preferred way to start things up?

**Comment by gilsheps** [comment] 2017-01-22 08:23
npm run dev works fine and the server load, if I don't ran build
But when I ran build, start there still error
[npm run build & npm start.txt](https://github.com/appium/appium-desktop/files/721804/npm.run.build.npm.start.txt)

**Comment by dpgraham** [comment] 2017-01-24 21:42
@gilsheps Can you try again with the latest? I've made some fixes related to this problem.

**Comment by gilsheps** [comment] 2017-01-26 12:11
@dpgraham I tried with the latest, still there issue after npm run build & npm start.
but this time after the build npm run dev works
[npm run build & npm start.txt](https://github.com/appium/appium-desktop/files/732219/npm.run.build.npm.start.txt)

**Comment by dpgraham** [comment] 2017-01-26 20:53
Yeah, I'm able to reproduce the issue too. When I have time I'll look into it more

**Comment by dpgraham** [comment] 2017-01-26 23:55
It's an Uglify problem.

The Babel transpiler is compiling the Javascript source and keeping fat arrows ```() => {}```, object shorthand ```{value}``` and this is being rejected by Uglify because it thinks it's invalid Javascript code.

This is only occurring on 'build-main' which is NodeJS. Does anyone know of any reason why we need to compress NodeJS code?

**Comment by jlipps** [comment] 2017-01-27 00:16
@dpgraham it gets bundled with the app I believe. But as this is open source I'd rather turn uglify off in any case.

**Comment by dpgraham** [comment] 2017-01-27 22:28
Fixed with dc6be8460fa36b298858532b00dc91ce7c10eded

**Closed by dpgraham** 2017-01-27 22:28 UTC
Labels: bug
