### ISSUE TITLE
Appium 1.8.0 - Inspector is not working with iOS native app, when we attach to session the appium is getting stopped

### ISSUE THREAD

**Issue by githubdilip** [appium/appium-desktop#563] opened 2018-06-08 06:55 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Using Appium 1.8.0 for iOS native app - Inspector is not working with iOS native app, when we attach to session the appium is getting stopped and session window get closed. 

## Environment

- I am running Appium Desktop version _1.8.0_.
- I am on (pick one):
    - [ ] Mac 10.13

**Comment by dpgraham** [comment] 2018-06-18 04:05
Can you provide server logs? Or is the application crashing?

**Comment by githubdilip** [comment] 2018-06-18 11:44
@dpgraham Application is getting crashed.

**Comment by EltonZhong** [comment] 2018-09-10 01:05
Got the same issue

**Comment by dpgraham** [comment] 2018-10-24 23:17
Does this happen with the latest?

**Comment by hoangtaiki** [comment] 2018-11-02 02:45
I got the same issue

**Comment by dpgraham** [comment] 2018-11-23 23:19
Closing as duplicate of: https://github.com/appium/appium-desktop/issues/669

**Closed by dpgraham** 2018-11-23 23:19 UTC
Labels: needsinfo
