### ISSUE TITLE
Automation of Apple Watch with Appium

### ISSUE THREAD

**Issue by moskaliukzhanna** [appium/appium-desktop#1769] opened 2021-04-13 17:33 UTC
Currently I am looking at the possibility to automate tests for Apple Watch using Appium. Since Xcode 12.5 beta already supports test targets for Apple Watch and Apple Watch can be tested with XCTest, I am concerned If there will be support for Apple Watch testing in Appium's next release?

**Comment by KazuCocoa** [comment] 2021-04-16 17:39
Duplicate of https://github.com/appium/appium/issues/4829

Potentially could if we add a new target for apple watch like tvOS. I haven't tested it via vanilla XCTest by Apple, so not sure exactly Appium also can do the same thing for now.

**Closed by KazuCocoa** 2021-04-16 17:39 UTC
