### ISSUE TITLE
Appium Inspector fails to return correct element stack using XCode 7.3/iOS 9.3.4

### ISSUE THREAD

**Issue by kirksl** [appium/appium-desktop#131] opened 2017-04-09 23:28 UTC
Please see the links below to a gist of my appium log and an image of what I see when using Appium Element Inspector using Appium Desktop. TestObject is the Appium Host.  Notice in the image that there are username and password fields along with a login button. The element inspection is returning all 3 of those controls under one element with all of the textual data lumped together.

**NOTE this issue was previously raised and closed at appium/appium and marked as an XCTest issue.  I don't believe this to be an XCTest issue as this happens with XCode 7.3 and logs are showing UIAuto instruments.**

https://github.com/appium/appium/issues/8171

XCode Version: 7.3 / UIAutomation
Appium version (or git revision) that exhibits the issue: 1.6.3
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: Windows 10 | OSX El Capitan
Node.js version (unless using Appium.app|exe): NA
Mobile platform/version under test: iOS 9.3.4
Real device or emulator/simulator: Real device on TestObject (iPad mini 3 16GB)
Appium CLI or Appium.app|exe: Appium Desktop 1.6.4-beta
Gist: https://gist.github.com/kirksl/ed571f947292e4e4f4d94594413a430c
Issue Screenshot: http://pasteboard.co/tKlxBCkD.png

**Comment by dpgraham** [comment] 2017-04-10 16:32
Have you tried Appium 1.6.4? (Appium 1.6.4 is built into Appium Desktop)

**Comment by dpgraham** [comment] 2017-04-10 16:37
https://i.ytimg.com/vi/XJ-ATwRq5KY/hqdefault.jpg

**Comment by kirksl** [comment] 2017-04-10 17:28
That was a great fight...  I get the error in the image below when I try 1.6.4 or 1.6.4-beta in capabilities from the latest Appium Desktop.

http://pasteboard.co/2GtzehVh3.png

**Comment by dpgraham** [comment] 2017-04-10 17:52
Apparently TestObject hasn't added 1.6.4 yet (which is understandable, we only released it a few days ago).

I think we should wait on that and then see what happens.

Have you tried running this test locally to see if the same problem occurs?

**Comment by kirksl** [comment] 2017-04-10 19:34
I haven't/can't at the moment.  Do you know when 1.6.4 will get added?  I'm also curious why we need 1.6.4 since this is not XCTest related.

**Comment by dpgraham** [comment] 2017-04-10 20:56
If it's not XCUITest problem then we won't be able to fix it, we've already stopped supporting anything before xcuitest.

Not sure when 1.6.4 will be out, depends on TestObject.

**Comment by kirksl** [comment] 2017-04-10 21:59
Is it possible to see if this issue goes away if we switch TestObject to XCode 8(currently it's using 7.3).  This will switch TestObject away from using UIAutomation to XCUITest.  Maybe via capabilities?

**Comment by dpgraham** [comment] 2017-04-10 22:19
@crummy Do you know the answer to this?

**Comment by crummy** [comment] 2017-04-11 07:52
If you want to force XCUITest, you can set the DesiredCapability of `automationName` to `xcuiTest`.

**Comment by kirksl** [comment] 2017-04-11 21:30
Thanks @crummy.  I tested both UIAutomation and XCUITest via capabilities in Landscape and Portrait against the latest Appium Desktop.  Screenshots below.  XCode is always set to 7.3.

**I still cannot successfully test or inspect iOS apps in landscape mode.  Any thoughts?  Xcode 8?  Maybe 1.6.4 will resolve this?**

UIA Portrait - http://pasteboard.co/38V1Naekk.png
XCUITest Portrait - http://pasteboard.co/juxsrlMG.png

UIA Landscape - http://pasteboard.co/38Wd6N2oP.png
XCUITest Landscape - http://pasteboard.co/38WCQdugm.png

**Comment by crummy** [comment] 2017-04-11 21:48
I couldn't say. Do you see the same behaviour when testing locally with a real device, off of TestObject? There shouldn't be any difference between an Appium server running on your own machine vs our end.

**Comment by kirksl** [comment] 2017-04-12 00:31
@crummy I can successfully inspect elements in landscape mode locally in my environment.  I'm on El Capitan 10.11.6, XCode 8.2.1, XCUITestDriver 2.23.1.  Real device is an iPad Mini 4.

**Comment by dpgraham** [comment] 2017-05-11 21:11
I'm going to close this as I don't believe there are any outstanding issues that need to be resolved.

**Closed by dpgraham** 2017-05-11 21:11 UTC

**Comment by kirksl** [comment] 2017-05-23 17:44
@dpgraham If it works in my local env and not in appium desktop why was this closed?

**Comment by dpgraham** [comment] 2017-05-23 20:04
It looks like the problem is with TestObject and not Appium Desktop. TestObject reports the source, AD just renders it. Have you tested locally _with_ Appium Desktop?

**Comment by kirksl** [comment] 2017-05-24 23:42
Thanks @dpgraham.  I'll take this up with the TO folks.  Local AD works...
