### ISSUE TITLE
Appium and Appium desktop are not taking the label name as the default accessibility id starting version 1.20

### ISSUE THREAD

**Issue by JamalMSaad** [appium/appium-desktop#1730] opened 2021-03-10 10:05 UTC
## The problem

Before release 1.20+ appium or appium desktop was taking the element label name as the default accessibility id,for example if we have a button with name "Test" and no accessibility id is defined for it,so  if we use the button name "Test" as the accessibility id , it was working fine in previous appium versions.

## Environment

- I am running Appium Desktop version 1.20.2.
- I am on (pick one):
    - [ ] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2021-03-13 22:54
duplicate of https://github.com/appium/appium-desktop/issues/1731

**Closed by KazuCocoa** 2021-03-13 22:54 UTC
