### ISSUE TITLE
i have problems building wda in real device with wda project inside appium desktop

### ISSUE THREAD

**Issue by HamzaMiz** [appium/appium-desktop#2130] opened 2022-11-23 09:35 UTC
## Appium or Appium Desktop?
You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ok ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

cannot link directly with dylib
for information , i fixed the same error on the appium npm  , i dowloaded the last xcuitestdriver , but here i cannot do that 
## Environment

- I am running Appium Desktop version _1.22.3_4
<img width="828" alt="Screenshot 2022-11-23 at 10 31 42" src="https://user-images.githubusercontent.com/94066399/203513175-482b3563-bb26-4f44-b4a5-cad15bb51801.png">
.
- I am on (pick one):
    - [ ok] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2022-11-24 01:12
duplicate of https://github.com/appium/appium-desktop/issues/2095

It occurs in Xcode 14 build. You need to run an appium server separately, then use https://github.com/appium/appium-inspector to inspect views.

**Closed by KazuCocoa** 2022-11-24 01:12 UTC
