### ISSUE TITLE
Java code generated by the Recorder contains syntax errors.

### ISSUE THREAD

**Issue by snewpeap** [appium/appium-desktop#1619] opened 2020-11-13 07:51 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Java code of 'Swipe/Tap By Coordinates' generated by the Recorder contains syntax errors:
```java
(new TouchAction(driver))
  .press({x: 327, y: 585})
  .moveTo({x: 1004: y: 921})
  .release()
  .perform()

(new TouchAction(driver)).tap(1100, 541).perform()
```
Both statements are missing semicolons, and that `press({x: 327, y: 585}).moveTo({x: 1004: y: 921})` statement is syntactically incorrect.

## Environment

- I am running Appium Desktop version 1.18.3.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2020-11-13 08:19
Duplicate of https://github.com/appium/appium-desktop/issues/1581

**Closed by KazuCocoa** 2020-11-13 08:19 UTC
