### ISSUE TITLE
Appium Desktop Window Does not Scroll Down

### ISSUE THREAD

**Issue by mojojojo94** [appium/appium-desktop#243] opened 2017-07-06 17:01 UTC
## Appium or Appium Desktop?
Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue -- Yes, Appium Desktop Issue

## The problem

Appium Inspector Window Does not scroll down -- selected elements section of the appium inspector window does not scroll down. This mean I cannot see all the attributes and information for a selected element.

## Environment

- I am running Appium Desktop version _1.1.0-beta.4_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by jlipps** [comment] 2017-07-06 17:20
duplicate of #236

**Closed by jlipps** 2017-07-06 17:20 UTC
