### ISSUE TITLE
Appium Inspector 'Refresh' - Error Unsupported MIME type, then get no screenshoot and no app source

### ISSUE THREAD

**Issue by jossets** [appium/appium-desktop#213] opened 2017-06-09 09:42 UTC
## Appium or Appium Desktop?
The issue occurs when using Appium inspector embedded in Appium Desktop with an android application with custom GUI component.

## The problem
Launch Appium-desktop
Start a new session
Start a session with (platform, platformversion, activity, package, devicename)
The apps starts on the android real device
Appium inspector show an initial  screenshoot and the app source.
I play with app , make some 'refresh' and get screenshoots and app sources.
When my app displays a custom video component with DRM control that doesnt allow screenshoots, pressing 'refresh' button generates an error message in Appium Inspector:
[takeScreenshot()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Unsupported MIME type:

And the console log trace:
[MJSONWP] Encountered internal error running command: Error: Unsupported MIME type:
at Jimp.throwError (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:82:43)
at Jimp.parseBitmap (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:307:31)
at /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/jimp/index.js:200:29
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

## Environment

- I am running Appium Desktop version _1.0.2-beta.2.
- I am on (pick one): Mac

## Workaround
When asked for a screenshot, the android part generates a buggy screenshoot file on the android file system, due to the custom component.
Appium Desktop uses adb to retireve this buggy file, then open it, load it and process it thanks to Jimp library (Java Image Processing).
The loaded image is processed by function parseBitmap(data, mime, cb) in  /Application/Appium.app/contents/Resources/app/node_modules/appium/node_modules/jimp/index.js

A switch (mime.toLowerCase()), chooses the function to process the file data depending on the file type.
It's not JPEG, nor BMP or PNG, so we enter the 'default:' case.
This default case generates an Error, then the app source dump stops, and we get only an error message.

We just made a quick workaround that works for us.
In the default case, we generate an empty green image the same size of the previous correct screenshoots.

At the beginning of the source file, add 2 global variable (changes in bold):
/Application/Appium.app/contents/Resources/app/node_modules/appium/node_modules/jimp/index.js

if (process.env.ENVIRONMENT !== "BROWSER") var FS = require("fs");
var PNG = require("pngjs").PNG;
var JPEG = require("jpeg-js");
var BMP = require("bmp-js");
var MIME = require("mime");
var TinyColor = require("tinycolor2");
var Resize = require("./resize.js");
var Resize2 = require("./resize2.js");
var StreamToBuffer = require("stream-to-buffer");
var ReadChunk = require("read-chunk");
var FileType = require("file-type");
var PixelMatch = require("pixelmatch");
var EXIFParser = require("exif-parser");
var ImagePHash = require("./phash.js");
var BigNumber = require('bignumber.js');
var URLRegEx = require("url-regex");
var BMFont = require("load-bmfont");
var Path = require("path");
**var _lastW=1;
var _lastH=1;**

at line 273, modify the 'default:' behavior.
// parses a bitmap from the constructor to the JIMP bitmap property
function parseBitmap(data, mime, cb) {
var that = this;
this._originalMime = mime;
switch (mime.toLowerCase()) {
case Jimp.MIME_PNG:
var png = new PNG();
png.parse(data, function(err, data) {
if (err) return throwError.call(that, err, cb);
that.bitmap = {
data: new Buffer(data.data),
width: data.width,
height: data.height
};
**_lastW=data.width;
_lastH=data.height;**
return cb.call(that, null, that);
});
break;
case Jimp.MIME_JPEG:
try {
this.bitmap = JPEG.decode(data);
exifRotate(this, data); // EXIF data
return cb.call(this, null, this);
} catch(err) {
return cb.call(this, err, this);
}
case Jimp.MIME_BMP:
this.bitmap = BMP.decode(data);
return cb.call(this, null, this);
**default:
this._originalMime = "Qk06AAAAAAAAADYAAAAoAAAAAQAAAAEAAAABABgAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAAEf8F/w==";
var buf = Buffer(this._originalMime, 'base64');
this.bitmap = BMP.decode(buf);
this.resize(_lastW,_lastH);
return cb.call(this, null, this);
//return throwError.call(this, "Unsupported MIME type: " + mime, cb);**
}
}

The _originalMime content is a base64 encoded 1 green pixel BMP.
This  1x1 green image  is then scaled to 1080x1920 if the previous correct screenshoot was 1080x1920.
The app source is fine as the Appium Inspector and the screenshoot is ful green.

**Comment by jlipps** [comment] 2017-06-09 16:15
@jossets thank you for the detailed report. However we don't control the jimp package, so we are unable to make the changes you applied. We will look into a way to return a more reasonable error, or perhaps just show a blank screenshot if the command fails, rather than erroring out. cc @dpgraham

**Comment by dpgraham** [comment] 2017-06-09 17:08
@jossets Does it break the session completely or do you just not get the screenshot at that point?

**Comment by jossets** [comment] 2017-06-10 07:10
As long as I have the custom UI component on my android view, I get no source and no screenshoot, but both app ans Inspector continues to works fine.
If I go to another view without the custom UI component and press 'Refresh' everything works fine.

**Comment by dpgraham** [comment] 2017-06-20 17:22
Closing as duplicate of https://github.com/appium/appium-desktop/issues/216

**Closed by dpgraham** 2017-06-20 17:22 UTC
