### ISSUE TITLE
 Unable to install web driver agent in iPhone 8(iOS 14.4) via MacOS BigSur with Xcode 12.4

### ISSUE THREAD

**Issue by ps1logi** [appium/appium-desktop#1692] opened 2021-02-12 12:59 UTC
## Appium Desktop

 Unable to install web driver agent in iPhone 8(iOS 14.4)
**Log** 
`An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: 2021-02-12 18:02:39.793 xcodebuild[25826:826649] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “WebDriverAgentRunner_iphoneos14.4-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/Users/ps1/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products/WebDriverAgentRunner_iphoneos14.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7f8332b8f450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}} ** TEST BUILD FAILED ** 2021-02-12 18:02:39.818 xcodebuild[25826:826651] IDETestOperationsObserverDebug: Writing diagnostic log for test session to: /Users/ps1/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.12_18-02-37-+0530.xcresult/Staging/2_Test/Diagnostics/WebDriverAgentRunner-06041868-1ADD-4667-80F0-933C1C39D8B6/WebDriverAgentRunner-2CBED791-BE99-40B5-A989-B57A771AE849/Session-WebDriverAgentRunner-2021-02-12_180239-rhBPfn.log 2021-02-12 18:02:39.820 xcodebuild[25826:826395] [MT] IDETestOperationsObserverDebug: (88698313-E096-4BC7-9171-37BC5BC34669) Beginning test session WebDriverAgentRunner-88698313-E096-4BC7-9171-37BC5BC34669 at 2021-02-12 18:02:39.819 with Xcode 12D4e on target 📱<DVTiOSDevice (0x7f833370bc20), iPhone8, iPhone, 14.3 (18C66), f77b83090cfdbf61525027dde949e1275fd18480> { deviceSerialNumber: F4JWM6HVJC67 identifier: f77b83090cfdbf61525027dde949e1275fd18480 deviceClass: iPhone deviceName: iPhone8 deviceIdentifier: f77b83090cfdbf61525027dde949e1275fd18480 productVersion: 14.3 buildVersion: 18C66 deviceSoftwareVersion: 14.3 (18C66) deviceArchitecture: arm64 deviceTotalCapacity: 56726433792 deviceAvailableCapacity: 53733060608 deviceIsTransient: NO ignored: NO deviceIsBusy: NO deviceIsPaired: YES deviceIsActivated: YES deviceActivationState: Activated isPasscodeLocked: NO deviceType: <DVTDeviceType:0x7f8332b7a4d0 Xcode.DeviceType.iPhone> supportedDeviceFamilies: ( 1 ) applications: (null) provisioningProfiles: (null) hasInternalSupport: NO hasWritableSystem: NO isSupportedOS: YES bootArgs: (null) nextBootArgs: (null) connected: YES isWirelessEnabled: NO connectionType: direct hostname: (null) bonjourServiceName: c0:b6:58:15:1b:27@fe80::c2b6:58ff:fe15:1b27._apple-mobdev2._tcp.local. activeProxiedDevice: (null) } (14.3 (18C66)) 2021-02-12 18:02:39.941 xcodebuild[25826:826395] [MT] IDETestOperationsObserverDebug: (88698313-E096-4BC7-9171-37BC5BC34669) Finished requesting crash reports. Continuing with testing. *** If you believe this error represents a bug, please attach the result bundle at /Users/ps1/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.12_18-02-37-+0530.xcresult 2021-02-12 18:02:39.969 xcodebuild[25826:826395] [MT] IDETestOperationsObserverDebug: 0.161 elapsed -- Testing started completed. 2021-02-12 18:02:39.969 xcodebuild[25826:826395] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start 2021-02-12 18:02:39.969 xcodebuild[25826:826395] [MT] IDETestOperationsObserverDebug: 0.161 sec, +0.161 sec -- end Test session results, code coverage, and logs: /Users/ps1/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.12_18-02-37-+0530.xcresult Testing failed: Building for iOS, but the linked and embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. Building for iOS, but the linked and embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. Building for iOS, but the embedded framework 'CocoaAsyncSocket.framework' was built for iOS + iOS Simulator. Building for iOS, but the embedded framework 'YYCache.framework' was built for iOS + iOS Simulator. WebDriverAgentRunner: WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/ps1/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Logs/Test/Test-WebDriverAgentRunner-2021.02.12_18-02-37-+0530.xcresult. (Underlying Error: The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file. The file doesn’t exist. (Underlying Error: The operation couldn’t be completed. No such file or directory))) ** TEST EXECUTE FAILED ** Testing started. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
`
I have done the following
* Removed the derive file of Xcode
* Remove and install Appium
* Remove webdriveragent in mobile
* Set Apple Dev license in Xcode 
* Run Script file for web driver agent location using terminal
* Verified device UUID, App Name, OS version, 
Example 
{
  "app": "com.js.au.qaApp",
  "platformName": "iOS",
  "platformVersion": "14.3",
  "udid": "f77b88900cfdbf61523427dde949e3456fd18480",
  "deviceName": "iPhone8",
  "automationName": "XCUITest"
}
## Environment

- I am running Appium Desktop version _<1.18.3>_.
- Environment
    - [X] Mac (BigSur OS 11.2.1)
    - [X] Python 3.9.1
    - [X] Node JS 12.16.3
    - [X] Xcode 12.4
    - [X] Robot Framework 3.2.2
    - [X] Cartage 0.37.0
    - [X] PyCharm 2020.3.3 (Community Edition) Build #PC-203.7148.72, built on January 27, 2021

**Comment by W446813** [comment] 2021-02-12 19:35
If you keep seeing errors about Cocoa issues and YYcache go to: 
1. WebDriverAgent left side under the file folder icon 
2. Click the WebDriverAgent icon under project
3. Select all from the search option and paste into the search bar exactly like this: VALIDATE_WORKSPACE
4. Set the Value to yes.

Re run the install to the phone again, following the same order.
WebDriverAgent library 
WebDriverAgentRunner 
Integration App


If you keep seeing errors about bundle identifiers go to: 
1. Integration app 
2. Info Tab 
3. Update Bundle identifier string to if it not set to this already:
$(PRODUCT_BUNDLE_IDENTIFIER)

**Comment by bradenbooks** [comment] 2021-02-12 19:40
If you keep seeing errors about Cocoa issues and YYcache go to: 
1. WebDriverAgent left side under the file folder icon 
2. Click the WebDriverAgent icon under project
3. Select all from the search option and paste into the search bar exacty like this: VALIDATE_WORKSPACE
4. Set the Value to yes.

Re run the install to the phone again, following the same order.
WebDriverAgent library 
WebDriverAgentRunner 
Integration App


If you keep seeing errors about bundle identifiers go to: 
1. Integration app 
2. Info Tab 
3. Update Bundle identifier string to if it not set to this already:
$(PRODUCT_BUNDLE_IDENTIFIER)

**Comment by ps1logi** [comment] 2021-02-13 06:29
@bradenbooks do I need to see WebDriverAgent in Xcode or Folder?

**Comment by bradenbooks** [comment] 2021-02-13 07:09
Oops sorry. Inside of appiums xcode. This one took me like three days to figgure out how to fix.

**Comment by KazuCocoa** [comment] 2021-02-13 07:17
You can try out Appium 1.20 for Xcode 12.3 and newer.
AppiumDesktop is now pre-release https://github.com/appium/appium-desktop/releases/tag/v1.20.2

Duplicate of https://github.com/appium/appium/issues/14952

`VALIDATE_WORKSPACE` could still help in some environments though.

**Comment by ps1logi** [comment] 2021-02-13 07:19
@bradenbooks thank I did follow the step told by you now webdriver is building in code but i am running using Appium Desktop I am getting this error 
`An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message: . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.`
Based the above error i tried search in google and found a youtube [video](https://www.youtube.com/watch?v=TprXEKBnfmA). Still, this error isn't fix

**Comment by ps1logi** [comment] 2021-02-13 08:29
@KazuCocoa issue got solved thank you

**Closed** 2021-02-13 09:37 UTC

**Comment by bsesella** [comment] 2021-04-26 08:00
> @KazuCocoa issue got solved thank you

How you solved this issue.... Still im getting same issue.. Can you please help to resolve that issue

**Comment by Norphy** [comment] 2021-07-02 08:10
@ps1logi Hi, would you mind sharing what you did to solve the issue in the end please?

**Comment by ps1logi** [comment] 2021-07-06 05:18
> @ps1logi Hi, would you mind sharing what you did to solve the issue in the end please?

I used AppiumDesktop is now pre-release https://github.com/appium/appium-desktop/releases/tag/v1.20.2

**Comment by drg407** [comment] 2021-10-30 23:38
> 3. Update Bundle identifier string to if it not set to this already:
>    $(PRODUCT_BUNDLE_IDENTIFIER)

THANK YOU! This stepped fixed it for me!
