### ISSUE TITLE
Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server.

### ISSUE THREAD

**Issue by SwarnagowriM** [appium/appium-desktop#1232] opened 2020-01-28 11:35 UTC
[appium_server_log.txt](https://github.com/appium/appium-desktop/files/4122116/appium_server_log.txt)
While running several test cases some of them suddenly fails with error creating session.

## The problem
Test fails when switching between adb command to appium.

## Environment

- I am running Appium 1.15.1
Python 3.8.1
- I am on (pick one):
    - [ ] Windows

**Comment by KazuCocoa** [comment] 2020-01-28 12:43
It looked the environment got new command timeout. Then, instrumentation had been closed. The behaviour was expected.
Did you increase the timeout with `newCommandTimeout`?

```
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"ed08cb65-c15f-4c22-92e1-00d2e4e119d4","value":"News"}
[info] [35m[WD Proxy][39m Replacing sessionId ed08cb65-c15f-4c22-92e1-00d2e4e119d4 with 114c4151-fdf0-4fd8-b960-8bd59de2f37d
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/114c4151-fdf0-4fd8-b960-8bd59de2f37d/element/96660714-b179-4e63-ad07-83ebeeb92398/text [39m[32m200[39m [90m24 ms - 67[39m
[info] [35m[HTTP][39m [90m[39m[warn] [35m[BaseDriver][39m Shutting down because we waited 5000 seconds for a command
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[warn] [35m[Appium][39m Closing session, cause was 'New Command Timeout of 5000 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[info] [35m[Appium][39m Removing session 7ef12783-8def-485e-9fb2-3eea09333875 from our master session list
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[debug] [35m[WD Proxy][39m Matched '/' to command name 'deleteSession'
[debug] [35m[WD Proxy][39m Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/00506b97-fcde-485b-b37f-1945fe1032db] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"00506b97-fcde-485b-b37f-1945fe1032db","value":null}
[debug] [35m[ADB][39m Running 'C:\Users\test\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s RDTSBHF00011081 shell am force-stop com.test'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[Logcat][39m Logcat already stopped
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'C:\Users\test\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s RDTSBHF00011081 forward --remove tcp\:8200'[info] [35m[UiAutomator2][39m Restoring hidden api policy to the device default configuration
[debug] [35m[ADB][39m Running 'C:\Users\test\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s RDTSBHF00011081 shell settings delete global hidden_api_policy_pre_p_apps'[debug] [35m[ADB][39m Running 'C:\Users\test\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s RDTSBHF00011081 shell settings delete global hidden_api_policy_p_apps'
[debug] [35m[Instrumentation][39m .
[debug] [35m[ADB][39m Running 'C:\Users\test\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s RDTSBHF00011081 shell settings delete global hidden_api_policy'[debug] [35m[Instrumentation][39m Time: 302.164
[debug] [35m[Instrumentation][39m 
[debug] [35m[Instrumentation][39m OK (1 test)[debug] [35m[Instrumentation][39m The process has exited with code 0[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/114c4151-fdf0-4fd8-b960-8bd59de2f37d/elements[39m
[info] [35m[HTTP][39m [90m{"using":"id","value":"com.test:id/title"}[39m
[debug] [35m[W3C (114c4151)][39m Calling AppiumDriver.findElements() with args: ["id","com.test:id/title","114c4151-fdf0-4fd8-b960-8bd59de2f37d"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 20000 ms for condition
[debug] [35m[WD Proxy][39m Matched '/elements' to command name 'findElements'
```


> Test fails when switching between adb command to appium.

Did you mean you handled different adb command? Then, restarting adb command could happen. The behaviour was also expected by adb.

btw, we recommend users to specify `automationName=UiAutomator2` for newer api versions

```
arn] [35m[Appium][39m ======================================================================
[warn] [35m[Appium][39m   DEPRECATION WARNING:
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The 'automationName' capability was not provided in the desired 
[warn] [35m[Appium][39m   capabilities for this Android session
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   Setting 'automationName=UiAutomator2' by default and using the 
[warn] [35m[Appium][39m   UiAutomator2 Driver
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   The next major version of Appium (2.x) will **require** the 
[warn] [35m[Appium][39m   'automationName' capability to be set for all sessions on all 
[warn] [35m[Appium][39m   platforms
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   In previous versions (Appium <= 1.13.x), the default was 
[warn] [35m[Appium][39m   'automationName=UiAutomator1'
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   If you wish to use that automation instead of UiAutomator2, please 
[warn] [35m[Appium][39m   add 'automationName=UiAutomator1' to your desired capabilities
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m   For more information about drivers, please visit 
[warn] [35m[Appium][39m   http://appium.io/docs/en/about-appium/intro/ and explore the 
[warn] [35m[Appium][39m   'Drivers' menu
[warn] [35m[Appium][39m 
[warn] [35m[Appium][39m ======================================================================
```

**Comment by mykola-mokhnach** [comment] 2020-01-28 12:47
@KazuCocoa This is a duplicate of https://github.com/appium/appium/issues/13873

**Comment by KazuCocoa** [comment] 2020-01-28 13:05
ah, nice. Thanks

**Closed by KazuCocoa** 2020-01-28 13:05 UTC
