### ISSUE TITLE
Ask to set ANDROID_HOME when already set

### ISSUE THREAD

**Issue by eliasnogueira** [appium/appium-desktop#48] opened 2017-03-02 17:16 UTC
## Problem
When I click in _Start Session_ I received the following message: _"An unknown server-side error occurred while processing the command. Original error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path."_

![message](https://cloud.githubusercontent.com/assets/284888/23518596/bec0b680-ff52-11e6-87f5-af571066d7a1.png)

But I have _ANDROID_HOME_ working on command line and in Android Studio
In the image bellow you can see my _ANDROID_HOME_ on _.bash_profile_ and the command _adb_ working

![my-settings](https://cloud.githubusercontent.com/assets/284888/23517576/8b1ae0ec-ff4f-11e6-9413-43ff90d98a1c.png)

On iOS platform I can start the emulator with no problems.

## Environment
- macOS Sierra 10.12.3
- Appium Desktop Beta 1.0.0-beta
- Appium Platform: Android
- Android SDK with:
 - API 23 (platform)
 - SDK Build Tools: 25.2.5
 - SDK Platform Tools: 25.0.3
 - SDK Build tools: 25.0.2, 24.0.2 

## Log
[appium-log.txt](https://github.com/appium/appium-desktop/files/814555/appium-log.txt)

**Comment by jlipps** [comment] 2017-03-02 17:50
thanks for reporting, looks like a dupe of #45.

**Closed by jlipps** 2017-03-02 17:50 UTC
