### ISSUE TITLE
Appium Desktop can't find opencv4nodejs

### ISSUE THREAD

**Issue by dcnt** [appium/appium-desktop#714] opened 2018-11-09 11:15 UTC
## Appium or Appium Desktop?
Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

While trying to compare images with Appium, it can't find installed opencv4nodejs module and raises exception:
```
[XCUITest] Executing command 'compareImages'
[W3C] Encountered internal error running command: Error: opencv4nodejs module is required to use OpenCV features. Please install it first (npm i -g opencv4nodejs) and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.
[W3C]     at initOpenCV (/Applications/Appium_1_8_2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/image-util.js:100:11)
...
```

But, it works in Appium Desktop 1.7.1 and appium-1.9.1.
opencv4nodejs module was installed with: npm install -g opencv4nodejs

## Environment

- I am running Appium Desktop version _1.8.2_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2018-11-13 17:39
What happens when you run `opencv4nodejs` from the terminal? Does it work then?

**Comment by dpgraham** [comment] 2018-11-13 18:34
Does it work if you run Appium 1.9.1 from the command line?

If it does, one workaround is to create a new session and point it to `Custom Server` that you have running on the command line.

**Comment by dcnt** [comment] 2018-11-13 18:42
> Does it work if you run Appium 1.9.1 from the command line?

Yes, it does

**Comment by dpgraham** [comment] 2018-11-13 19:29
I would recommend running sessions from command line then and using the inspector: `Appium -> New Session Window` and then selecting `Custom Server`.

**Comment by dpgraham** [comment] 2018-11-13 19:29
That would be a workaround until I have time to investigate this.

**Comment by dcnt** [comment] 2018-11-13 19:51
@dpgraham 
thanks

**Comment by vkuhi** [comment] 2018-12-21 12:53
@dpgraham @dcnt Did you solve this issue because I have the same problem?

**Comment by dcnt** [comment] 2018-12-21 13:17
@vkuhi 
Still doesn't work. Tested with Appium Desktop 1.9.0 on several setups.

**Comment by KazuCocoa** [comment] 2018-12-21 17:09
If the `opencv4nodejs ` module exists in `Appium.app/Contents/Resources/app/node_modules`, it probably works.

I tried to install `opencv4nodejs` under there modifying and installing it in `Appium.app/Contents/Resources/app/package.json` via termianl, but I have not confirmed it yet because I failed to install it there...

**Comment by sme81** [comment] 2019-12-09 10:23
Sorry for reviving this but it's the only issue showing up in search.

Was any working solution to this ever found?

Appium CLI 1.15.1, with 'npm install -g opencv4nodejs' works.

However I have tried the same with Appium Desktop which results in the error 

> 'Encountered internal error running command: Error: opencv4nodejs module is required to use OpenCV features. Please install it first (npm i -g opencv4nodejs) and restart Appium.'

I have tried 'npm link opencv4nodejs' within various node_modules folders as mentioned above but get the same error. Any help, greatly appreciated!

**Comment by ivantay2003** [comment] 2019-12-10 03:48
@sme81  - I had this problem , but found a solution . 

You have to install libdevicelocation first then install opencv4nodejs. I am not certain why , but it works for me. 

I have document this in the [article](https://medium.com/@ivantay2003/setting-up-appium-in-os-x-ecd9e7108a9c) , look under section 2

**Comment by sme81** [comment] 2019-12-10 09:55
This looks like a substantial/lengthy install procedure, hope it works on appium desktop after

**Comment by avenstewart** [comment] 2021-09-08 15:34
This issue is currently affecting Appium 1.21.0 on Mac OS Big Sur 11.5.2. Currently unable to use any Appium features that utilize openCV as a result. Opencv4nodejs is installed and this is confirmed by Appium-doctor. I have tried every suggested solution to remedy this bug to no avail. Building the package manually does not help. 

```
[Support] Failed to load global package 'opencv4nodejs': The "path" argument must be of type string. Received type undefined
[Support] Linking package 'opencv4nodejs'
[Support] Unable to load package 'opencv4nodejs', linking failed: Command 'npm link opencv4nodejs' exited with code 1
[Support] npm ERR! Tracker "idealTree" already exists
[Support] 
[Support] npm ERR! A complete log of this run can be found in:
[Support] npm ERR!     /Users/astewart/.npm/_logs/2021-09-07T23_55_31_556Z-debug.log
[Support] 
[Support] Unable to load package 'opencv4nodejs': Unable to load package 'opencv4nodejs', linking failed: Command 'npm link opencv4nodejs' exited with code 1
[Support] Unable to load 'opencv4nodejs': Unable to load package 'opencv4nodejs': Unable to load package 'opencv4nodejs', linking failed: Command 'npm link opencv4nodejs' exited with code 1
[W3C (95d27a5c)] Encountered internal error running command: Error: 'opencv4nodejs' module is required to use OpenCV features. Please install it first ('npm i -g opencv4nodejs') and restart Appium. Read https://github.com/justadudewhohacks/opencv4nodejs#how-to-install for more details on this topic.```

**Comment by avenstewart** [comment] 2021-09-08 15:37
It is also worth noting the idevicelocator is not currently able to compile properly on Big Sur due to newer node error handling deprecations, and the developers have not committed anything in a long time.

**Comment by rrudiuk-devx** [comment] 2021-11-16 15:33
Hi. Are there any updates on that?

**Comment by VP-QA** [comment] 2021-11-29 05:47
window 10 

installed opencv4nodejs@5.6.0

run appium 

and run testcode 
but met errror   Original error: 'opencv4nodejs' module is required to use OpenCV features

why~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jhonjhon95** [comment] 2023-01-30 17:41
alguma novidade sobre ?

**Comment by jlipps** [comment] 2023-01-30 19:15
this project is no longer supported, and appium no longer uses opencv4nodejs. use appium 2 and the appium inspector instead.

**Closed by jlipps** 2023-01-30 19:15 UTC
Labels: bug, enhancement, help wanted, P2

**Comment by jhonjhon95** [comment] 2023-01-30 21:14
@jlipps in this case, to use opencv4nodejs, do I just need to switch to appium 2?

**Comment by jhonjhon95** [comment] 2023-01-31 12:26
basically to validate that an image is the same as a screnshot. Could you tell me the name of this plugin for appium2?

**Comment by jlipps** [comment] 2023-01-31 20:37
https://github.com/appium/appium/tree/master/packages/images-plugin
