### ISSUE TITLE
Original error: '<appName>' is still running after 500ms timeout

### ISSUE THREAD

**Issue by jphennessey** [appium/appium-desktop#644] opened 2018-09-27 19:33 UTC
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When using Appium Desktop ONLY the following call...
`((AndroidDriver)((WebDriverFacade) getDriver()).getProxiedDriver()).terminateApp("<appName>");`

...yields the following exception...
`[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - The following error occurred: An unknown server-side error occurred while processing the command. Original error: '<appName>' is still running after 500ms timeout`

With Appium CLI, there is no exception and my tests run fine.

## Environment

- I am running Appium Desktop version _<1.7.1.20180926.9>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by vikramvi** [comment] 2018-09-28 07:56
appium CLI version : 1.9.0

Appium Desktop Version : 1.7.1

After every test case execution, we're closing the app and re-opening before test case starts. This is to make sure app has got clean base state.

**Comment by vikramvi** [comment] 2018-10-01 14:41
@dpgraham can you please have a look at this issue ?

**Comment by dpgraham** [comment] 2018-10-24 23:30
@jphennessey Do you have a sample app + capabilities to reproduce this?

**Comment by dpgraham** [comment] 2018-11-23 23:16
I'll re-open if sample app + caps provided.

**Closed** 2018-11-23 23:16 UTC
Labels: needsinfo

**Comment by hellojanice** [comment] 2019-03-18 05:44
Still exists the issue in appium1.10.0, when the app stay in first level screen, it do not report error.But if app stay in second level screen, it will report the exception "step error message is: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'com.glip.mobile' is still running after 500ms timeout".

**Comment by SNagaPavan** [comment] 2019-04-09 07:44
We are also facing the same issue. @dpgraham Can you please provide some solution to it.

CC: @jphennessey @vikramvi

**Comment by shethpradeep** [comment] 2020-06-24 16:45
@dpgraham - Pls use the API Demos app. Click "OS" button, Click "SMS Messaging" button. Now try to terminate the app using "driver.terminateApp("provide app package name"); ", you will get the error "Encountered internal error running command: Error: 'io.appium.android.apis' is still running after 500ms timeout"

**Comment by halbii** [comment] 2020-07-07 15:02
The same happens for me with the native settings app when executing driver.terminate_app("com.android.settings"). Increasing the timeout does not solve the problem and just ignoring the exception is fine, since the app actually closes and can be reopened later. 

Additional, possibly helpful info: 

- Only happens with the settings app, not with other apps opened/closed during the session. 
- Behavior not dependent on the "appPackage" or "appActivity" capabilities.

Setup: 
- Appium CLI v1.17.1 on a Windows PC
- Appium-Python-Client==1.0.1 
- Android 9 on a Galaxy Tab A

Caps:
{
  "platformName": "Android",
  "platformVersion": "9",
  "automationName": "uiautomator2",
  "appPackage": "com.android.settings",
  "appActivity": ".Settings",
  "deviceName": "Galaxy Tab A",
  "noReset": "True",
  "fullReset": "False"
}

**Comment by PhilippSelenium** [comment] 2020-10-29 10:02
@dpgraham What is missing for reopening this issue?
