### ISSUE TITLE
Error: Unable to launch WebDriverAgent because of xcodebuild failure

### ISSUE THREAD

**Issue by denysvoskovets** [appium/appium-desktop#380] opened 2018-01-11 17:55 UTC
## The problem
Updated desktop Appium version from 1.7.1 to 1.7.2. It asked to move Appium into Application folder(I moved). After that it doesn't work. I'm receiving this error in logs but i'm not clearly understand how to fix it.

## Environment
Appium version (or git revision) that exhibits the issue: 1.7.2
Desktop OS/version used to run Appium: MacOs Sierra 10.12.6
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS
Real device or emulator/simulator: Simulator iPhone6s 11.2
Appium CLI or Appium.app|exe:
## Details
Error:
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at
Error: Unable to launch WebDriverAgent because of xcodebuild failure: "ENOENT: no such file or directory, open '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h'".
at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at

Link to Appium logs
Logs attached.

https://gist.github.com/denysvoskovets/739d7cf7b55f0994c76c1b3bfc36fe94

**Comment by imurchie** [comment] 2018-01-11 18:24
Duplicate of #378 and #379. A fix is in the works.

**Closed by imurchie** 2018-01-11 18:24 UTC
