### ISSUE TITLE
after downloading latest apium desktop 1.15,popup alert displaying to update older verison 1.13

### ISSUE THREAD

**Issue by rkn411** [appium/appium-desktop#1113] opened 2019-10-04 07:59 UTC
## Environment
![Screenshot 2019-10-04 at 3 57 11 pm](https://user-images.githubusercontent.com/18478260/66191019-e2386700-e6bf-11e9-984c-7afbaf0ef222.png)
@imurchie @jlipps @mykola-mokhnach 

- I am running Appium Desktop version _<1.15>_.
- I am on (pick one):
    - [ ] Mac

**Comment by KazuCocoa** [comment] 2019-10-04 12:49
Thanks.

This is duplicate of https://github.com/appium/appium-desktop/issues/1042
https://github.com/appium/appium-desktop/releases (It is because 1.14 and 1.15 is pre-release)

**Closed by KazuCocoa** 2019-10-04 12:49 UTC
