### ISSUE TITLE
The appium desktop inspector crashes. This happens when attaching to an existing session.

### ISSUE THREAD

**Issue by rcuyugan** [appium/appium-desktop#669] opened 2018-10-12 20:53 UTC
Mac OS High Sierra
Appium 1.9.1
Appium Server 1.7.1

This was also happening on version 1.8 but a workaround was applied by adding capabilities.setCapability("forceMjsonwp", true);

Now even with that workaround enabled, the inspector still crashes and closes out server when inspecting.

Steps to repro:
Open the inspector
Attach to an existing session
Inspect
Appium crashes and closes

**Comment by dpgraham** [comment] 2018-10-22 20:36
Can you give me a simple test to reproduce this issue?

**Comment by krirohini** [comment] 2018-10-24 05:46
i am also facing the same issue 

Could not obtain source: {"cause":{"sessionId":"63c6d7a3-17c8-4de8-820f-b22378213284","status":13,"value":{"message":"An unknown server-side error occurred while processing the command."}},"jsonwire-error":{"detail":"An unknown server-side error occurred while processing the command.","status":13,"summary":"UnknownError"},"message":"[source()] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command.","status":13}

**Comment by dpgraham** [comment] 2018-10-24 16:46
@krirohini Can you provide a test script to reproduce this issue?

**Comment by MoOoG** [comment] 2018-11-07 10:43
+1
We are also facing the same issue. I'm sorry but I can not provide a test script to reproduce this.

**Comment by dpgraham** [comment] 2018-11-09 00:18
I'm going to try to put in a fix for this for the next Appium version... but for now, I recommend reverting to an older client version that doesn't use W3C.

**Comment by MoOoG** [comment] 2018-12-05 08:12
Just tested again with new Appium version (1.10.0) and Appium Desktop (1.9.0) but the crash is still there.

**Comment by dpgraham** [comment] 2018-12-06 17:17
Yeah, I'm working on swapping out the underlying client so that it supports W3C.

**Comment by krirohini** [comment] 2018-12-13 19:49
Still getting the same error.

**Comment by dpgraham** [comment] 2018-12-13 21:21
@krirohini I haven't fixed it yet

**Comment by dpost** [comment] 2018-12-14 20:32
@dpgraham I believe this is duplicated by #722 

I've also obtained the error from the dev server when it crashes using my steps to reproduce there:

> [2] uncaughtException: no value passed to Element constructor
[2] Error: no value passed to Element constructor
[2]     at PromiseElement.Element (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/element.js:15:11)
[2]     at new PromiseElement (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/promise-webdriver.js:73:20)
[2]     at PromiseWebdriver.newElement (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/promise-webdriver.js:103:12)
[2]     at /Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/callbacks.js:156:24
[2]     at /Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/callbacks.js:101:7
[2]     at /Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/webdriver.js:183:5
[2]     at Request._callback (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/wd/lib/http-utils.js:89:7)
[2]     at Request.self.callback (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/request/request.js:185:22)
[2]     at Request.emit (events.js:182:13)
[2]     at Request.<anonymous> (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/request/request.js:1161:10)
[2]     at Request.emit (events.js:182:13)
[2]     at IncomingMessage.<anonymous> (/Users/david.lumpkin/src/misc/appium-desktop/node_modules/request/request.js:1083:12)
[2]     at Object.onceWrapper (events.js:273:13)
[2]     at IncomingMessage.emit (events.js:187:15)
[2]     at endReadableNT (_stream_readable.js:1090:12)
[2]     at process._tickCallback (internal/process/next_tick.js:63:19)

I have a bit of JS experience and can also try to take a look at fixing this if you don't already have a patch

**Comment by dpgraham** [comment] 2018-12-20 18:56
Can people try 1.9.1.... I'm pretty sure this problem should be resolved now. If not, let me know and I'll re-open.

**Closed by dpgraham** 2018-12-20 18:56 UTC
Labels: P1, bug

**Comment by MoOoG** [comment] 2018-12-21 07:19
It works for me, both platforms. Thank you so much!

**Comment by EltonZhong** [comment] 2019-01-18 03:02
> Can people try 1.9.1.... I'm pretty sure this problem should be resolved now. If not, let me know and I'll re-open.

Please re-open.

**Comment by EltonZhong** [comment] 2019-01-18 03:06
[The appium desktop inspector crashes. This happens when attaching to an existing session. ](https://github.com/appium/appium-desktop/issues/669)
[https://github.com/appium/appium-desktop/issues/536](https://github.com/appium/appium-desktop/issues/536)
and the issues are closed with the bug reproducing on version: Version 1.10.0.

Jan 15 14:16:32 lmxmn150 com.apple.xpc.launchd[1] (io.appium.desktop.9084[56019]): Service exited with abnormal code: 1

Still reproduced when I choose an element.
Appium version: Version 1.10.0 (1.10.0.20181230.2)
macOS High sierra 10.13.6

**Comment by bhadmus** [comment] 2019-11-01 13:57
> @dpost Yes, the change to W3C for Appium Server caused the problem. The internal client that A.D. uses is `admc/wd` which doesn't support W3C. The solution is to either port the client over to use WebdriverIO or update `admc/wd` to support W3C. And yeah, you're welcome to look at it, I haven't started yet.

How can I achieve this? I am experiencing this with Appium 1.15.1
