### ISSUE TITLE
Appium Server GUI not opening in Mac

### ISSUE THREAD

**Issue by harishvgk** [appium/appium-desktop#2035] opened 2022-04-29 10:15 UTC
## Appium Desktop

I downloaded the Appium Desktop for Mac from https://github.com/appium/appium-desktop/releases/download/v1.22.3/Appium-Server-GUI-mac-1.22.3.dmg

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

After installation, I tried to open the app. I am getting this error

<img width="270" alt="Screenshot 2022-04-29 at 3 14 39 PM" src="https://user-images.githubusercontent.com/57757173/165925859-9f9e310b-469d-4df5-a2a6-38913bb3e801.png">

## Environment

- I am running Appium Desktop version Version 1.22.3 (1.22.3.20220328.1), Mac OS - Monterey
- I am on (pick one):
    - [x] Mac

**Comment by jlipps** [comment] 2022-05-02 21:38
duplicate of https://github.com/appium/appium-desktop/issues/2024

**Closed by jlipps** 2022-05-02 21:38 UTC
