### ISSUE TITLE
After running for some time, the console becomes very slow

### ISSUE THREAD

**Issue by jushiyuan** [appium/appium-desktop#135] opened 2017-04-12 03:16 UTC
After running for some time, the appium-desktop console becomes very slow, is it because there are too many logs? In addition to restart the server, is there any other solution? Thanks.

**Comment by jlipps** [comment] 2017-04-12 16:51
@jushiyuan how long are we talking? It could be because there are too many logs. Maybe we want to start cutting them off at some point.

**Comment by dem0n0cracy** [comment] 2017-04-12 21:56
Hey I can confirm this is happening to me too. The window is completely unresponsive - I can't scroll up or down, I can't click Start New Session or Stop Server. Have to restart to make it useable again. That said, the server is still running. Version 1.0.0 testing iOS.

**Comment by jushiyuan** [comment] 2017-04-13 00:37
@jlipps If keep running test cases,that happens after about 1 hour.

**Comment by jlipps** [comment] 2017-04-13 20:53
Good to know. @dpgraham we should add this to the list.

**Comment by dpgraham** [comment] 2017-04-13 22:46
Which OS are you two running it on?

**Comment by dem0n0cracy** [comment] 2017-04-13 22:49
Sierra latest updates. I only just left so I cant provide better info until tomorrow.

**Comment by dpgraham** [comment] 2017-04-13 23:06
Thanks. I just wanted to know which OS to try and reproduce it on.

**Comment by jushiyuan** [comment] 2017-04-14 00:41
@dpgraham yes,Sierra latest updates too.

**Comment by monsam** [comment] 2017-06-09 15:08
I am facing this issue after running tests overnight,  AppiumHelper process is growing to 2GB and ui stops responding. I suspect log size is making the app unresponsive, may be discard older logs?

**Comment by jlipps** [comment] 2017-06-09 15:56
Yes, we will add it to our list to remove old logs after a certain number of lines have been reached, so things stay responsive.

**Comment by dpgraham** [comment] 2017-08-04 17:22
Fixed by https://github.com/appium/appium-desktop/pull/263

Logs are now limited to 1000, but you can download the entire logs as a text file.

**Closed by dpgraham** 2017-08-04 17:22 UTC
Labels: bug, P1

**Comment by monsam** [comment] 2017-08-05 02:55
This is great

**Comment by dpgraham** [comment] 2017-08-08 18:12
Awesome! @monsam Did this fix problems you were having?
