### ISSUE TITLE
inspector.appiumpro crashes after start session

### ISSUE THREAD

**Issue by shut-serg-tester** [appium/appium-desktop#2062] opened 2022-06-21 15:45 UTC
## Appium

Web version of Appium Inspector (https://inspector.appiumpro.com/) crashes after start session

## The problem

Unhandled Exception
An unexpected error occurred with message: Cannot set properties of undefined (setting 'default').
Please kindly open up a bug report at https://github.com/appium/appium-desktop/issues/new.
TypeError: Cannot set properties of undefined (setting 'default')
    at _regeneratorRuntime (https://inspector.appiumpro.com/renderer.e31bb0bc.js:62981:19)
    at https://inspector.appiumpro.com/renderer.e31bb0bc.js:82368:135
    at fk (https://inspector.appiumpro.com/renderer.e31bb0bc.js:917:359)
    at exports.unstable_runWithPriority (https://inspector.appiumpro.com/renderer.e31bb0bc.js:643:343)
    at gg (https://inspector.appiumpro.com/renderer.e31bb0bc.js:777:325)
    at Oj (https://inspector.appiumpro.com/renderer.e31bb0bc.js:916:308)
    at https://inspector.appiumpro.com/renderer.e31bb0bc.js:916:215
    at V (https://inspector.appiumpro.com/renderer.e31bb0bc.js:641:224)
    at F.port1.onmessage (https://inspector.appiumpro.com/renderer.e31bb0bc.js:637:346)

**Comment by jlipps** [comment] 2022-06-22 19:35
duplicate of https://github.com/appium/appium-inspector/issues/477

**Closed by jlipps** 2022-06-22 19:35 UTC
