### ISSUE TITLE
Cannot create an iOS session using Appium Desktop

### ISSUE THREAD

**Issue by kevin-roe** [appium/appium-desktop#1578] opened 2020-10-01 21:27 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop fails to create session for iOS

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

## Steps to Reproduce

Given Appium Desktop v. 1.18.0-2
And Carthage v. 0.36.0
And Xcode v. 12.0.1
When I use the following desired capabilities in Appium Desktop:
```
{
  "platformName": "iOS",
  "deviceName": "iPhone 11",
  "automationName": "XCUITest",
  "app": "/Users/me/path/to/MyApp.iOS.app"
}
```
Then I receive the following error in the Appium desktop server logs
```
[WebDriverAgent] Build Failed
[WebDriverAgent] 	Task failed with exit code 1:
[WebDriverAgent] 	/usr/bin/xcrun lipo -create /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket
[WebDriverAgent] This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/m8/6tkks5hs0z994mfh0ny0qp5rj0v__b/T/carthage-xcodebuild.sN2atv.log
[BaseDriver] Event 'wdaStartFailed' logged at 1601580150514 (14:22:30 GMT-0500 (Central Daylight Time))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[iOSSim] Building bundle path map
[iOSSim] The simulator has '0' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[WebDriverAgent] No WDAs on the device.
[XCUITest] {}
[DevCon Factory] Releasing connections for FBA4D866-FA3A-4D91-9D31-B9E305BAB15C device on any port number
[DevCon Factory] Found cached connections to release: ["FBA4D866-FA3A-4D91-9D31-B9E305BAB15C:8100"]
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[IOSSimulatorLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1601580150527 (14:22:30 GMT-0500 (Central Daylight Time))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS\,tvOS' exited with code 1
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:532:15)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:562:11
[MJSONWP]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[MJSONWP]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[MJSONWP]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:542:7
[MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 239139 ms - 269
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 7 ms - 57
```

## Notes
I am able to execute a test using the Appium command line utility (v. 1.18.2)

**Comment by sme81** [comment] 2020-10-01 21:33
Same issue on ios 14 simulator

**Comment by kroe761** [comment] 2020-10-01 21:36
Thank you sme81, I forgot to mention that I am also testing on iOS 14.

**Comment by KazuCocoa** [comment] 2020-10-02 02:24
Duplicate of https://github.com/appium/appium-desktop/issues/1567

It is expected so far since the version does not have newer Appium. https://github.com/appium/appium-desktop#connect-to-local-appium-server is the way to connect to the local appium server (not Appium Desktop's embedded appium).
I just waited for v1.18.3, but probably will push 1.18.2 of Appium Desktop.

**Closed by KazuCocoa** 2020-10-02 02:24 UTC
