### ISSUE TITLE
Could not download update. Try again later.

### ISSUE THREAD

**Issue by amitsainani** [appium/appium-desktop#109] opened 2017-03-29 21:17 UTC
![image](https://cloud.githubusercontent.com/assets/334439/24477053/728890ba-148a-11e7-93d5-d14ba235b78b.png)

**Comment by vikramvi** [comment] 2017-03-31 09:47
duplicate of https://github.com/appium/appium-desktop/issues/90

**Closed** 2017-04-04 17:24 UTC
