### ISSUE TITLE
Custom XPath validator on Appium-desktop as we had previously

### ISSUE THREAD

**Issue by Prasant-Sutaria** [appium/appium-desktop#110] opened 2017-03-30 20:24 UTC
In old Appium UI, under Object Spy we had a utility which validated custom XPATH. It will be a good feature for the Appium desktop object spy as well.

We can add a Custom XPATH validator or we can add option to select selector type and provide value to validate against current screen.

**Comment by dpgraham** [comment] 2017-03-31 17:46
Yeah, we've talked about something like that before. My idea was a search modal where you select a locator strategy (xpath, name, id, etc...) and then input a locator and it lists the elements that meet that criteria.

**Comment by reuningATL** [comment] 2017-04-06 14:52
Xpath is quite useful because we have many elements in our app that are not tagged or exactly assessable.

**Comment by mvanini** [comment] 2017-04-26 11:01
👍  for this missing fundamental missing feature

**Comment by dpgraham** [comment] 2017-05-17 23:03
Hey @mvanini @reuningATL @Prasant-Sutaria 

We added a new feature that calculates an XPath for an element (see https://github.com/appium/appium-desktop/commit/413018388d9b7d489c7211d1ffe4a8867aedfe25) and it does heuristics to determine the "optimal" xpath.

Is this sufficient or do you think we should add another feature which allows the user to actually test xpaths?

**Comment by vanangelov** [comment] 2017-05-18 06:45
I personally think the feature that heuristically optimizes the automatically generated xpath is a great idea, but in my opinion it does not remove the need for the capability to test custom xpaths.
For example sometimes I find the need for to do things like 'following-sibling::' in the xpath to keep it short and meaningful.

**Comment by mvanini** [comment] 2017-05-18 06:50
same as @vanangelov for me: sometimes I use "complex" xpath, it would be usefull to test into the inspector instead running (long) appium-test.

**Comment by dpgraham** [comment] 2017-07-13 18:27
Closing as duplicate of: https://github.com/appium/appium-desktop/issues/202

**Closed by dpgraham** 2017-07-13 18:27 UTC
Labels: enhancement

**Comment by 3dmundbarton** [comment] 2017-07-26 22:31
I know this is a closed issue, but the following the references all the linked tickets are closed too.  Please consider re-opening it.

The ability to check a custom Xpath is not a nice to have part of a test automation framework, it is essential.  Otherwise you fall back on dumb, time consuming trial and error.  There was a feature in the previous version of appium-desktop which enabled validation of custom Xpaths, which was awesome - I believe it is an essential feature of the new one too.  As a user, I commonly extract xpaths from the app, but just as often (during maintenance / triage of scripts) validate my coded xpaths against the app. 

@dpgraham @jlipps 
btw - great work on the new version of a-d, script recording in windows ftw! just add xpath checking and we're onto a winner

**Comment by jlipps** [comment] 2017-07-26 22:57
We closed this since the feature has been implemented. It just hasn't been released yet. If you build from master you will see the element finding feature which can be used to find elements via xpath.

**Comment by 3dmundbarton** [comment] 2017-08-02 21:58
Great stuff, so I've reviewed the find feature in the latest build, I guess what I'm looking at is a feature request then.  
Listing the elements and being able to tap, clear, sendkeys is great - how about highlighting the matches in the screenshot and application XML?  
This would mean that you can see what your xpath refers to, and would a massive productivity enhancement for those of us maintaining appium-based suites.  
Are you considering enhancements at this stage?

**Comment by dpgraham** [comment] 2017-08-03 16:50
@3dmundbarton Thanks for reviewing it, I appreciate the positive feedback!

One of the limitations we deal with is that when you search for elements using Appium it returns a list of element ID's but doesn't give any information other than that so we can't actually link the elements returned in the search results with the XML node in the source tree.

What I could possibly do is make it so that when you select an element in the list, it fetches that element's bounds and then highlights it in the screenshot (although I don't think we could highlight the source XML node for the reason stated in the above paragraph). I agree it would be helpful to actually know which element you're clicking on.
