### ISSUE TITLE
Compiler flag error for XCode 12 Beta 4 and Appium 18.0.1

### ISSUE THREAD

**Issue by DGandalf** [appium/appium-desktop#1517] opened 2020-08-11 05:43 UTC
- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

During the first compilation of the WebDriverAgent-runner there is a failure when calling lipo!

The Appium-Output looks like this :

[WebDriverAgent] *** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
[WebDriverAgent] Build Failed
[WebDriverAgent] 	Task failed with exit code 1:
[WebDriverAgent] 	/usr/bin/xcrun lipo -create /Users/dominikpaulmichl/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/dominikpaulmichl/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium_18_0_1.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket
[WebDriverAgent] This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jk/vv259qls1njgdw3s5qfhgc9w0000gp/T/carthage-xcodebuild.o0P23x.log

But the log file states that the **build has been successfully finished**.

When calling the /usr/bin/xcrun lipo -create.... command in the Terminal (copy and paste)
then the output of lipo is :
CocoaAsyncSocket have the same architectures (arm64) and can't be in the same fat output file

Seems for me, that the appium xcodeproj files or lipo (?) are missing a (new?) build flag to build for one architecture only.

## Environment

- I am running Appium Desktop version _18.0.1_.
- I am on (pick one):
    - [X] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment] 2020-08-11 05:54
Duplicate of https://github.com/appium/appium/issues/14611

**Closed by KazuCocoa** 2020-08-11 05:54 UTC
