### ISSUE TITLE
The docs are either incomplete or incorrect

### ISSUE THREAD

**Issue by jaipaddy** [appium/appium-desktop#50] opened 2017-03-02 19:49 UTC
1. Refer [https://github.com/appium/appium-desktop](url) and follow each step to the T. I see my app logo on the iPhone Simulator but it dies on launch
2. On starting the session, I see 

```
[XCUITest] The app has been installed successfully.
[XCUITest] Carthage not found. Install using `brew install carthage`
```
3. But `brew install carthage` failed on macOS Sierra, so had to install the .pkg from [https://github.com/Carthage/Carthage](url)

4. Try starting the session again, and I see the same messages as in 2.

5. DesiredCapabilities set were 
{
  "platformName": "iOS",
"platformVersion": "10.2",
"deviceName": "iPhone Simulator",
 "app": "/Users/ME/Downloads/iOSapp.ipa",
 "noReset": true,
 "xcodeConfigFile": "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig"
}

I know this is supposed to be a beta version but it seems to be a blocker out of the box.

**Comment by dkdodson3** [comment] 2017-03-02 20:36
Did you try updating brew?

I installed carthage today with brew and I am on sierra. The v1.0.0-beta of the app is working for me on iOS.

The carthage installed with NPM does not work with appium, I wonder if the latest on github is the same as the one in NPM.

**Comment by jaipaddy** [comment] 2017-03-02 21:28
Still no luck, although brew update worked for me this time and I was able to install carthage. But it appears as though the app crashes right away despite a 200 response- 

`[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage not found. Install using `brew install carthage`
[XCUITest] Killing hanging processes
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=B8DF25D2-1870-488D-8AA4-4FD7E351F5A3 -configuration Debug' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[XCUITest] Log file for xcodebuild test: /Users/JaiPadmanabhan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cvqckynzuuktkogfpkkkgyompmoj/Logs/Test/E82B9AA8-EB10-4BEC-A5BD-321D492295CD/Session-WebDriverAgentRunner-2017-03-02_162304-nox77J.log
[XCUITest] WebDriverAgent running on ip '192.168.52.125'
[XCUITest] WebDriverAgent successfully started after 13718ms
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"192.168.52.125\"\n    },\n    \"build\" : {\n      \"time\" : \"Mar  2 2017 13:13:48\"\n    }\n  },\n  \"sessionId\" : \"5683370A-BC32-45EA-ACA1-49F20B976B86\",\n  \"status\" : 0\n}"
`

**Comment by dpgraham** [comment] 2017-03-02 21:40
Is the entire app crashing or just the session window?

**Comment by jaipaddy** [comment] 2017-03-02 21:47
Inside the simulator, the app opens and dies right away. This continues every few minutes. How can I try this on a real device? Desiredcapabilities - uuid is a server level property and throws an exception complaining about uuid being specified. In the previous appium UI, this was a checkbox.

**Comment by imurchie** [comment] 2017-03-02 21:51
This looks to be the same as the rest of the ones today, where the environment is not replicated inside the app.

**Comment by jlipps** [comment] 2017-03-02 22:17
Yes, looks like a dupe of #45. See my last comment there. You can re-download from the releases page and get a version that I think fixes the issue.

**Closed by jlipps** 2017-03-02 22:17 UTC
