### ISSUE TITLE
e.replace is not function error - UI inspector for IOS

### ISSUE THREAD

**Issue by yogevglucome** [appium/appium-desktop#767] opened 2018-12-11 14:37 UTC
Flow:
Open Appium for Mac (1.9.0)
Attach to session (Current session is iPhone 6 on XCODE)

Error displayed: e.replace is not a function
<img width="996" alt="screen shot 2018-12-11 at 16 35 03" src="https://user-images.githubusercontent.com/32836288/49807563-0eff4480-fd63-11e8-8d9f-9774fdcb86c5.png">

**Comment by dpgraham** [comment] 2018-12-11 22:34
Can you provide the Appium logs for when that happens?

**Comment by dpgraham** [comment] 2019-01-10 18:13
Closing. Will re-open if logs provided.

**Closed by dpgraham** 2019-01-10 18:13 UTC
Labels: needsinfo

**Comment by iammike** [comment] 2019-03-11 18:27
A coworker and I receive this error quite often. Sometimes the inspector can be closed and a new session started, others the whole server needs to come down. Using 1.9.1. Will add logs next time it happens.

**Comment by iammike** [comment] 2019-03-11 20:53
`[HTTP] --> GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd
[HTTP] {}
[W3C (b3e053b1)] Calling AppiumDriver.getSession() with args: ["b3e053b1-f04f-40fe-bbb4-95a457099cbd"]
[UiAutomator2] Getting session details from server to mix in
[JSONWP Proxy] Matched '/' to command name 'getSession'
[JSONWP Proxy] Proxying [GET /] to [GET http://localhost:8209/wd/hub/session/324d2cb9-669b-4870-b1b8-93709377a05c] with body: {}
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8209}
[W3C (b3e053b1)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8209
[W3C (b3e053b1)]     at JWProxy.command (/Applications/Appium_1_9_1.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13)
[HTTP] <-- GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd 500 5 ms - 591
[HTTP] 
[HTTP] --> GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/source
[HTTP] {}
[W3C (b3e053b1)] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/source' to command name 'getPageSource'
[JSONWP Proxy] Proxying [GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/source] to [GET http://localhost:8209/wd/hub/session/324d2cb9-669b-4870-b1b8-93709377a05c/source] with body: {}
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8209}
[W3C (b3e053b1)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8209
[W3C (b3e053b1)]     at doJwpProxy (/Applications/Appium_1_9_1.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:547:13)
[HTTP] <-- GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/source 500 8 ms - 795
[HTTP] 
[HTTP] --> GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/screenshot
[HTTP] {}
[W3C (b3e053b1)] Calling AppiumDriver.getScreenshot() with args: ["b3e053b1-f04f-40fe-bbb4-95a457099cbd"]
[JSONWP Proxy] Matched '/screenshot' to command name 'getScreenshot'
[JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8209/wd/hub/session/324d2cb9-669b-4870-b1b8-93709377a05c/screenshot] with no body
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8209}
[W3C (b3e053b1)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8209
[W3C (b3e053b1)]     at JWProxy.command (/Applications/Appium_1_9_1.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:236:13)
[HTTP] <-- GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/screenshot 500 5 ms - 591
[HTTP] 
[HTTP] --> GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/window/current/size
[HTTP] {}
[W3C (b3e053b1)] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/window/current/size' to command name 'getWindowSize'
[JSONWP Proxy] Proxying [GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/window/current/size] to [GET http://localhost:8209/wd/hub/session/324d2cb9-669b-4870-b1b8-93709377a05c/window/current/size] with body: {}
[JSONWP Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8209}
[W3C (b3e053b1)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8209
[W3C (b3e053b1)]     at doJwpProxy (/Applications/Appium_1_9_1.app/Contents/Resources/app/node_modules/appium-base-driver/lib/protocol/protocol.js:547:13)
[HTTP] <-- GET /wd/hub/session/b3e053b1-f04f-40fe-bbb4-95a457099cbd/window/current/size 500 4 ms - 795
[HTTP] `

**Comment by dpgraham** [comment] 2019-03-11 22:29
The next version will have improvements to the error messaging. I'm pretty sure the problem is just that the error message being displayed is not helpful.

**Comment by mrk-han** [comment] 2019-06-28 18:51
![image](https://user-images.githubusercontent.com/22263679/60364426-24ad2200-99b4-11e9-9f23-2f8cfe957ff2.png)

**Comment by mrk-han** [comment] 2019-06-28 18:51
Same error, this is the last log
