### ISSUE TITLE
Appium inspector couldn't start session

### ISSUE THREAD

**Issue by kuhivchak** [appium/appium-desktop#1919] opened 2021-10-04 08:48 UTC
## Appium Inspector

Using JSON file in not possible in Appium inspector yet. On Appium desktop build inside inspector 1.21 - works fine.
{
  "platformName": "Android",
  "deviceName": "emulator-5554",
  "newCommandTimeout": "18000",
  "appActivity": "com.mediteo.mobile.presentation.main.RootActivity",
  "appWaitActivity": "com.mediteo.mobile.presentation.login.LoginActivity,com.mediteo.mobile.presentation.main.RootActivity,com.mediteo.mobile.presentation.main.MainActivity, com.mediteo.mobile.presentation.onboarding.activity.OnboardingActivity",
  "appName": "app-rc.apk",
  "automationName": "uiautomator2",
  "autoGrantPermissions": "true",
  "language": "en",
  "locale": "UK"
}

## The problem

Error: 
Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

Also _Attach to Session..._ is not working and cannot find any session. But appium is started and works fine.
<img width="1269" alt="Screenshot 2021-10-04 at 11 36 47" src="https://user-images.githubusercontent.com/17832231/135820780-0680b2ed-fecf-408d-bb4b-ea0067f018fc.png">

## Environment

- I am running Appium Inspector version: _App Version: 2021.9.1_
Electron: _13.4.0_
Node.js: _14.16.0_
MacOS: _BigSur 11.2.1_
Appium: _1.22_ and also checked on _1.21_

**Comment by KazuCocoa** [comment] 2021-10-04 09:05
Duplicate of https://github.com/appium/appium/discussions/15890#discussioncomment-1384248
Current your inspector has `/` as the remote path.

**Closed by KazuCocoa** 2021-10-04 09:05 UTC
