### ISSUE TITLE
Appium desktop running for some time, always inexplicable crash, Mac os 10.11.6, appium desktop 1.0.0 beta.4

### ISSUE THREAD

**Issue by zhaozhiquan** [appium/appium-desktop#104] opened 2017-03-28 04:08 UTC

**Comment by jlipps** [comment] 2017-03-28 17:04
Can you provide any more information, @zhaozhiquan? I'm not sure what you're reporting exactly.

**Comment by zhaozhiquan** [comment] 2017-03-29 03:07
When I use the appium desktop to run the script, or use the start of a new session to debug, or start server to do other things. Appium desktop may quit， if you need a log, please tell me the log is there where i uploaded to you

**Comment by dpgraham** [comment] 2017-04-03 16:27
Can you check the Appium desktop logs?

(app name is appium-desktop)

```
on Linux: ~/.config/<app name>/log.log
on OS X: ~/Library/Logs/<app name>/log.log
on Windows: %USERPROFILE%\AppData\Roaming\<app name>\log.log
```

Also, is the desktop application crashing or is the server crashing?

**Comment by jushiyuan** [comment] 2017-04-13 00:41
@zhaozhiquan 更新到最新版本就好了，我这也有这情况。

**Comment by zhaozhiquan** [comment] 2017-04-13 01:30
@dpgraham   is the desktop application crashing .But I updated to the latest version did not appear after, and in ~ / Library / Logs did not find appium-desktop

**Comment by dpgraham** [comment] 2017-04-13 16:40
Is it still crashing when you use the latest version?

**Comment by dpgraham** [comment] 2017-07-19 21:36
Closing this as duplicate of: https://github.com/appium/appium-desktop/issues/135

I think it's related to server logs building up without being cleared.

**Closed by dpgraham** 2017-07-19 21:36 UTC
Labels: bug
