### ISSUE TITLE
Could not cache the response identified by ''

### ISSUE THREAD

**Issue by iceman545** [appium/appium-desktop#1656] opened 2020-12-25 07:40 UTC
## The problem

The Appium app crashed when running a test case for iOS on Mac OS.

## Environment

* Appium version: 1.19.1
* Desktop OS/version used to run Appium: Mac OS 10.15.5
* Node.js version: 14.15.1
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details
Below is the screenshot of the Appium log:
![image](https://user-images.githubusercontent.com/11288896/103125762-1c2bc980-46c7-11eb-9d49-646754a7ff89.png)
Then the app crashed.

**Comment by mykola-mokhnach** [comment] 2020-12-28 10:14
It's a duplicate of https://github.com/appium/appium/issues/14952

**Closed** 2020-12-28 10:24 UTC
