### ISSUE TITLE
Windows Desktop App Source shown properly on V1.17.0 - later versions are bad.

### ISSUE THREAD

**Issue by robtail** [appium/appium-desktop#1722] opened 2021-03-05 13:43 UTC
## Appium Desktop

- [x ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
App Source shows all elements corresponds to app started by Appium in Appium Desktop Version 1.17.0 but all the latest versions shows only a subset of the source. I used same Windows Application Driver for all test so it is not WAD issue.
Screen shows how source should look like. This source representation is for v1.17.0:
![image](https://user-images.githubusercontent.com/77631362/110122812-61076700-7dc0-11eb-9fc4-eb0dc4ce00b8.png)

This screen shows less element in source - this is for v1.17.1-1:
![image](https://user-images.githubusercontent.com/77631362/110123201-e428bd00-7dc0-11eb-9a63-2a49890a9d0c.png)

## Environment

- I am running Appium Desktop version 1.17.0. 
- I am on (pick one):
    - [x ] Windows

**Comment by KazuCocoa** [comment] 2021-03-05 18:18
Duplicate of https://github.com/appium/appium-desktop/issues/1653

**Closed by KazuCocoa** 2021-03-05 18:18 UTC
