### ISSUE TITLE
Invalid code generation

### ISSUE THREAD

**Issue by igasparis** [appium/appium-desktop#693] opened 2018-10-30 19:05 UTC
## Appium or Appium Desktop?
- I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
When you generate code for JS - Webdriver.io and the show/hide boilerplate code option is enabled, the generated code is `.com")` instead of `.setValue("foo@foo.com")` as long as the sent text contains an email address.

## Environment

- I am running Appium Desktop version 1.8.0.
- I am on Linux

**Comment by dpgraham** [comment] 2018-10-30 19:55
I'll have a look when I get a chance, thanks for reporting this!

**Comment by dpgraham** [comment] 2018-10-30 20:11
I just tried and wasn't able to reproduce this. How did you do it?

**Comment by igasparis** [comment] 2018-10-30 20:21
I press `Start Recording`, click on a text field, press `Send Keys` and type any email. Then use `JS - Webdriver.io` and press the `Show/Hide boilerplate code`. 
This is a screenshot - it happens to every single android app at least: 

![screenshot from 2018-10-30 15-19-18](https://user-images.githubusercontent.com/29467766/47747827-3ab4e800-dc57-11e8-9e9a-e74957d876ca.png)

**Comment by dpgraham** [comment] 2018-10-30 20:23
I can repro it now thanks.

It was because I wasn't showing the boilerplate.

**Comment by dpgraham** [comment] 2018-11-01 20:12
Closed as fix

**Closed by dpgraham** 2018-11-01 20:12 UTC
Labels: bug
