### ISSUE TITLE
Unable to launch on Real device - Error: Unknown device or simulator UDID: 'XXXXXXXXXXX'

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium-desktop#47] opened 2017-03-02 09:43 UTC
Hello,

I recently downloaded the Appium desktop version and trying to launch my app in iOS 10.2.1 (real device) but I am getting an error. My desired capabilities is as below

{
  "automationName": "XCUITest",
  "deviceName": "iPad",
  "platformName": "iOS",
  "app": "/xxxxxx.ipa",
  "platformVersion": "10.2.1",
  "udid": "XXXXXXXXX",
  "xcodeOrgId": "XXXXXXX",
  "xcodeSigningId": "iPhone Developer"
}

FYI -  I have installed the latest ideviceinstaller and libimobiledevice. And running the "idevice_id -l" command in the terminal displayes a list of connected devices

I am getting the below error 

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/xxx.ipa","automationName":"XCUITest","deviceName":"iPad","platformName":"iOS","platformVersion":"10.2.1","udid":"XXXXXX","xcodeOrgId":"XXXXX","xcodeSigningId":"iPhone Developer","newCommandTimeout":0},null,null,null,null]
[Appium] Creating new XCUITestDriver (v2.12.1) session
[Appium] Capabilities:
[Appium]   app: '/xxx.ipa'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPad'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2.1'
[Appium]   udid: 'XXXXXX'
[Appium]   xcodeOrgId: 'XXXXX'
[Appium]   xcodeSigningId: 'iPhone Developer'
[Appium]   newCommandTimeout: 0
[XCUITest] XCUITestDriver version: 2.12.1
[BaseDriver] Session created with session id: 4e39fafe-3fe3-450e-bfb1-fe41a10c8d04
[XCUITest] Xcode version set to '8.2.1'
[XCUITest] iOS SDK Version set to '10.2'

[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'

[XCUITest] Available devices: 

[XCUITest] Error: Unknown device or simulator UDID: 'XXXXXXXX'
    at XCUITestDriver.determineDevice$ 

(/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/lib/driver.js:530:17)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Please help

**Comment by imurchie** [comment] 2017-03-02 12:21
This line gives you a clue to the problem: `[XCUITest] The 'idevice_id' program is not installed. If you are running a real device test it is necessary. Install with 'brew install libimobiledevice --HEAD'`.

Try installing `libimobiledevice` with the command `brew install libimobiledevice --HEAD`.

**Comment by jlipps** [comment] 2017-03-02 19:01
Yes, either @imurchie's suggestion is the solution, or this is a dupe of #45.

**Closed by jlipps** 2017-03-02 19:01 UTC

**Comment by Arjunkalidas** [comment] 2017-04-13 08:32
https://gist.github.com/Arjunkalidas/050dc299d76e47fc62e47ee34ab13667

I am unable to install the ipa in iphone. I have ideviceinstaller and I am able to install the same through terminal, but it's failing to launch with Appium. Please have a look at the log file link above.

**Comment by jlipps** [comment] 2017-04-13 20:36
@Arjunkalidas please create a new issue with your details

**Comment by BShivShankar** [comment] 2018-07-06 10:06
Hi @poorvikamahesh if you still facing the same error after running the command 'brew install libimobiledevice --HEAD' then the problem is not about device id

If you are running appium server from code, here follow the steps below to fix this issue

1. In terminal give command 'echo $PATH'
 2. Then copy the entire path
3. In your eclipse or other tool script, where you are running the class (java) file go to run configuration - select which class java file you are and then click on environment click -> New -> give the name as PATH and for value give the entire path. Then run the class file  

If you still have any other concern or any issue get me https://www.linkedin.com/in/shiv-shankar-siddarth/
thanks
