### ISSUE TITLE
appium desktop: tap,sendkeys,clear buttons are disable for every element in my App

### ISSUE THREAD

**Issue by Shahunks** [appium/appium-desktop#319] opened 2017-10-18 11:06 UTC
## Appium or Appium Desktop? - Appium Desktop

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ yes] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The problem

appium desktop: tap,sendkeys,clear buttons are disable for every element in my App

Environment

Appium version (or git revision) that exhibits the issue:1.6.5
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: MAC OS
Node.js version (unless using Appium.app|exe):6.10.1
Mobile platform/version under test: 8.0.0
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: appium.app
## Environment

- I am running Appium Desktop version 1.7.1
![screen shot 2017-10-18 at 3 32 43 pm](https://user-images.githubusercontent.com/25055088/31715693-79c4762c-b422-11e7-924b-0cd4558f666b.png)

- I am on (pick one):
     Mac

**Comment by dpgraham** [comment] 2017-10-18 16:18
Can you open up the dev tools (F12) and look what happens in the console logs when you select an element?

**Comment by Shahunks** [comment] 2017-10-18 17:05
well, there is nothing that happens in dev tools when i select element and all the Attributes value is false.
![screen shot 2017-10-18 at 3 32 43 pm](https://user-images.githubusercontent.com/25055088/31732006-90f1be22-b454-11e7-8a37-a08b241e3e58.png)

**Comment by dpgraham** [comment] 2017-10-18 17:10
In dev tools, is there a tab called `Redux`? 

That shows the logs for the application.

**Comment by Shahunks** [comment] 2017-10-18 17:19
I don't see a Redux tab.
![screen shot 2017-10-18 at 10 48 43 pm](https://user-images.githubusercontent.com/25055088/31732566-91376b5a-b456-11e7-9174-4aad1d586881.png)

**Comment by dpgraham** [comment] 2017-10-18 17:31
Right, it's not available in prod.

**Comment by Shahunks** [comment] 2017-10-18 17:32
So what could be the issue, user name text box is greyed out

**Comment by dpgraham** [comment] 2017-10-19 17:14
Can you try selecting an element and then sending me the Appium logs?

You should see something like this:

```
[MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeApplication[@name=\"UICatalog\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[6]","ea58194a-ef20-4aaf-b055-815fc9ea81b5"]
[XCUITest] Executing command 'findElements'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/2B7EB500-6A56-4CB5-BEC1-46035C44D316/elements] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[@name=\"UICatalog\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[6]"}
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"0FFBB84E-7788-4A63-8378-938293B1BA92"}],"sessionId":"2B7EB500-6A56-4CB5-BEC1-46035C44D316","status":0}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"0FFBB84E-7788-4A63-8378-938293B1BA92"}]
[HTTP] <-- POST /wd/hub/session/ea58194a-ef20-4aaf-b055-815fc9ea81b5/elements 200 1635 ms - 124 
```

**Comment by Shahunks** [comment] 2017-10-23 03:53
yes, 
[MJSONWP] Responding to client with driver.findElements() result: []

This is the log for the element which is disabled.

**Comment by dpgraham** [comment] 2017-10-23 04:48
Can you show me the logs prior to that? I think what's happening is that it's not finding the element because the element is stale.

Can you also try hitting the 'Refresh' button? That usually fixes problems with stale elements. Perhaps, we need to make Appium Desktop do that automatically when it fails to find an element.

**Comment by dpgraham** [comment] 2017-10-23 05:04
Actually, you don't need to show any more logs... I think I know the issue.

The element is stale. I'm putting in a PR that automatically refreshes the source whenever you select a stale element.

**Comment by Shahunks** [comment] 2017-10-23 05:06
Even on refresh the element is not available to click

**Comment by dpgraham** [comment] 2017-10-23 13:23
Okay, can you show me the full logs then? I'd like to see the logs of when you click on the element and what selector it uses to find it.

Does your app have a UI that fluctuates often? This happens when what is on the actual app is different from what's in the screenshot/source.

**Comment by Shahunks** [comment] 2017-10-24 06:26
here is the log - https://gist.github.com/Shahunks/26a6c6b27deb60c15a2906e44d41c3e7

No my app doesn't have any UI that Fluctuates, this is the main login text box which is not enabled 
its a Hybrid app.

**Comment by dpgraham** [comment] 2017-10-24 06:41
Are you able to send us a copy of the app? If I can run it on my side and reproduce it I could probably find the problem.

**Comment by Shahunks** [comment] 2017-10-24 06:44
Its in Play/ App store , App Name:  Zapty

**Comment by dpgraham** [comment] 2017-10-24 06:52
Okay. Yeah I'll have a look at that tomorrow morning (I'm on PST). Is it the main page that you can reproduce the issue?

**Comment by Shahunks** [comment] 2017-10-24 06:57
yes this is the page
![screen shot 2017-10-24 at 12 26 21 pm](https://user-images.githubusercontent.com/25055088/31928679-a53df272-b8b6-11e7-87b0-8f8431fff288.png)

**Comment by dpgraham** [comment] 2017-10-24 17:47
Okay, I can reproduce it now. Looks like an Appium Desktop issue.

I should be able to fix it.

Thanks for your help on this!

**Comment by dpgraham** [comment] 2017-10-24 18:00
I just tried it with the latest version and I'm able to reproduce.

Interestiingly, this is only happening with `automationName=UIAutomator2`. 

I should be able to come up with some fix/workaround for this problem. Thanks for your help on this!

**Comment by dpgraham** [comment] 2017-10-24 20:18
Fix will be released next version in the next day or so

**Closed by dpgraham** 2017-10-24 20:18 UTC
Labels: enhancement, P1

**Comment by Shahunks** [comment] 2017-10-25 04:58
thank you

**Comment by dpgraham** [comment] 2017-10-25 05:20
No problem. Thanks for helping me with this.

**Comment by Shahunks** [comment] 2017-10-26 06:40
@dpgraham : now the fix is available in A.D i can click , send keys to the home page sign in screen,
But when i copy the selectors from A.D and use the selectors in my script and run (using WDIO runner) the element is not located . m not understanding why is that happening?

**Comment by Shahunks** [comment] 2017-10-26 07:20
In Android 6.0 i have a different xpath and in Android 7.1.1 & 8.0.0 i have another xpath btw none of the xpath works

**Comment by dpgraham** [comment] 2017-10-26 18:36
That's what the problem was. The selectors that A.D. autogenerates weren't working so I made it fall back to other selectors. I would look into the Appium Logs and see when you select an element which strategy/selector is being used.

**Comment by dpgraham** [comment] 2017-10-26 18:37
Also... is this problem reproducible in Android 6, 7 and 8?

I wonder if a later version of Android broke it.

**Comment by Shahunks** [comment] 2017-10-27 03:37
Well, the problem is reproducible in Android 6 & 7 which has same Xpath for the same element with out resource id and in 8 different xpath with resource id.
Now, if i use the xpath from 6& 7 doesn't work running against it as well the 8 xpath neither works. 
Earlier the same xpath form 6 or 7 was working when running form the script.
Problem is when i updated the A.D and to Android 8.

**Comment by samsonbarukula** [comment] 2017-11-03 14:17
appium desktop I have tried with ios 11 ipad, it always disabled... 1.2.6 version  any help

**Comment by karnan008** [comment] 2018-05-02 08:14
@dpgraham 
Am with iOS mobile application testing.
I face the same issue in iOS with a simulator of iPhone 6 with OS of 11.0

Can you please give us the solution for this nearly am struck with this from 2month ago
