### ISSUE TITLE
Desktop :windows 10 Home Single Language.Appium version 1.5(latest) crash-not at all opening

### ISSUE THREAD

**Issue by AgoBalan** [appium/appium-desktop#483] opened 2018-04-04 15:47 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

_Replace this section with a description of your issue_

## Environment windows 10 Home Single Language

- I am running Appium Desktop version _<1.5>_.
- I am on (pick one):
    - [ ] Mac
    - [o] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2018-04-04 16:20
Can you try enabling long paths on your Windows machine:

https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

**Comment by dpgraham** [comment] 2018-04-04 21:40
Will close as duplicate of: https://github.com/appium/appium-desktop/issues/482

**Closed by dpgraham** 2018-04-04 21:40 UTC
