### ISSUE TITLE
Appium inspector loses test session to cloud device silently

### ISSUE THREAD

**Issue by LasseHall** [appium/appium-desktop#498] opened 2018-04-18 17:16 UTC
- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Appium Desktop's session inspector enables users to connect to cloud devices. Cloud device sessions however limit newCommandTimeout to certain values, which causes the sessions to silently close behind the scenes. The inspector tool currently sets newCommandTimeout to 0 and expects to have a never-ending session available.

## Environment

- I am running Appium Desktop version 1.5.0
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2018-04-18 18:52
I've thought about how we should do this...

I think we should have the Appium session pinging the server every 30 seconds to stay alive but then in the UI check if the user has been inactive for 5 minutes and if they have, prompt them with a modal asking them if they wish to keep the session alive.

**Comment by dpgraham** [comment] 2018-04-18 18:53
If No --> quit the session
If Yes --> restart the 5 minute timer

**Comment by dpgraham** [comment] 2018-04-25 16:32
Will be in next version

**Closed by dpgraham** 2018-04-25 16:32 UTC
Labels: P1, enhancement

**Comment by CAPie** [comment] 2019-02-19 12:03
@dpgraham hi, just to clarify: what If I not click any button, session will interrupted anyway =(

it looks quite annoying. I really suffer with this patch.
My workflow looks like: I'm starting the session (installing the app), login, go to some view to get some needed locators (xpath / accessibilityId's) after that I'm going to IDE to write some code (it takes more than 5 mins / I do not see the prompt) then I come back to appium - Session interrupted =( 
all stuff again

I've tried to set the `newCommandTimeout: 1800` (30 min) in desires caps but session anyway is interrupted in 5 mins.
My question is: how to configure the appium do not interrupt the session in 5 min? may I run it from console with some flags, or change some config manually to increase this timeout?

**Comment by dpgraham** [comment] 2019-02-19 17:53
@CAPie I can look at this again... can you open a new issue with steps to reproduce and a description of the problem.
