### ISSUE TITLE
Appium-ios 13 simulators:sometimes, clicking on element is taking too long to respond

### ISSUE THREAD

**Issue by Ravikiran-ml** [appium/appium-desktop#1103] opened 2019-10-01 12:44 UTC
I am using appium with ruby, after upgrading xcode from 10 to 11, after clicking on elements is taking too long

Appium: 1.15.1
xcode:11
ios: ios-13 iPhone 8 plus

Refer: logs: 
Element Found:**/XCUIElementTypeButton[$name='Done'$][$visible==1$][1]
[HTTP] --> POST /wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element
[HTTP] {"using":"-ios class chain","value":"**/XCUIElementTypeButton[$name='Done'$][$visible==1$][1]"}
[debug] [W3C (a2fbe727)] Calling AppiumDriver.findElement() with args: ["-ios class chain","**/XCUIElementTypeButton[$name='Done'$][$visible==1$][1]","a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [WD Proxy] Matched '/element' to command name 'findElement'
[debug] [WD Proxy] Proxying [POST /element] to [POST http://localhost:8602/session/C5B74F34-C343-4C29-A8DB-26AC3121EDCE/element] with body: {"using":"class chain","value":"**/XCUIElementTypeButton[$name='Done'$][$visible==1$][1]"}
[debug] [WD Proxy] Got response with status 200: {"value":{"ELEMENT":"F1030000-0000-0000-DE09-000000000000","element-6066-11e4-a52e-4f735466cecf":"F1030000-0000-0000-DE09-000000000000"},"sessionId":"C5B74F34-C343-4C29-A8DB-26AC3121EDCE"}
[debug] [W3C (a2fbe727)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"F1030000-0000-0000-DE09-000000000000","ELEMENT":"F1030000-0000-0000-DE09-000000000000"}
[HTTP] <-- POST /wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element 200 731 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element/F1030000-0000-0000-DE09-000000000000/click
[HTTP] {}
[W3C (a2fbe727)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element/F1030000-0000-0000-DE09-000000000000/click' to command name 'click'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element/F1030000-0000-0000-DE09-000000000000/click] to [POST http://localhost:8602/session/C5B74F34-C343-4C29-A8DB-26AC3121EDCE/element/F1030000-0000-0000-DE09-000000000000/click] with body: {}
[HTTP] <-- POST /wd/hub/session/a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c/element/F1030000-0000-0000-DE09-000000000000/click - - ms - -
[HTTP] 
[debug] [WD Proxy] Got response with status 200: {"value":null,"sessionId":"C5B74F34-C343-4C29-A8DB-26AC3121EDCE"}
[WD Proxy] Replacing sessionId C5B74F34-C343-4C29-A8DB-26AC3121EDCE with a2fbe727-1c79-4dc4-b40f-ce64ea1dfa2c

**Comment by KazuCocoa** [comment] 2019-10-22 10:21
Could you share the log with `showIOSLog`?
If the element is in WebView element, it is a possible duplicate of https://github.com/appium/appium/issues/13455 , I guess

**Comment by testmonk** [comment] 2019-11-11 07:48
@KazuCocoa This issue is still observed on version 1.15.1.

**Comment by matepp** [comment] 2019-11-11 09:11
@KazuCocoa We don't use WebView type and the element location is still take much more time than before :/

**Comment by matepp** [comment] 2019-11-11 09:23
I recognized that i can reach every element on the Appium inspector on the background. So if i have a login page, after the login page our app load a dashboard and  in the inspector i can locate the sign in fields. Before xcode 11 and ios 13 that was not possible.
<img width="166" alt="Screenshot 2019-11-11 at 10 18 44" src="https://user-images.githubusercontent.com/22351540/68575877-4db6e680-046d-11ea-90aa-f8fe7340bbd6.png">

**Comment by KazuCocoa** [comment] 2019-11-11 09:30
We cannot say anything without logs with `showIOSLog`.
Appium waits for the response by XCTest framework by Apple in general element queries/interactions. Mostly Apple can improve the performance.

Logs help us to detect the cause of the slowness is the Apple framework side stuff.

**Comment by matepp** [comment] 2019-11-11 09:44
Getting the page source take too long i think:

W3C (0f5a7c92)] Calling AppiumDriver.getPageSource() with args: ["0f5a7c92-027a-495a-a95c-5a328fdaca43"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [WD Proxy] Matched '/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/F6C92812-57A5-4BB9-8617-898667FBB82D/source] with no body
[debug] [WD Proxy] Got response with status 200: {
[debug] [WD Proxy]   "value" : "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"XY\" label=\"XY\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1024\" height=\"1366\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n        <XCUIElementTypeImage type=\"XCUIElementTypeImage\" name=\"background.png\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\"\/>\n        <XCUIElementTypeButton type=\"XCUIElementTypeButton\" name=\"selector_button\" enabled=\"true\" visible=\"true\" x=\"30\" y=\"34\" width=\"...
[debug] [W3C (0f5a7c92)] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><AppiumAUT><XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"XY\" label=\"XY\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1024\" height=\"1366\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\">\n        <XCUIElementTypeImage type=\"XCUIElementTypeImage\" name=\"background.png\" enabled=\"true\" visible=\"false\" x=\"0\" y=\"0\" width=\"1366\" height=\"1024\"/>\n        <XCUIElementTypeButton type=\"XCUIElementTypeButton\" name=\"selector_button\" enabled=\"true\" visible=\"true\" x=\"30\" y=\"34\" width=\"50\" h...
[HTTP] <-- GET /wd/hub/session/0f5a7c92-027a-495a-a95c-5a328fdaca43/source 200 6494 ms - 53037

**Comment by KazuCocoa** [comment] 2019-11-11 09:52
Appium resolves visibility etc in source command. It takes time since it tries to get element attributes recursively to build the source tree (and converts them as XML format)

You can get debugDescription directly as a text with https://github.com/appium/appium/issues/12818#issuecomment-506063025 command. It does not have some element information such as visibility.

**Comment by KazuCocoa** [comment] 2020-08-15 09:37
Close since this is not AD specific issue like the above comment

**Closed by KazuCocoa** 2020-08-15 09:37 UTC
