### ISSUE TITLE
cannot start the application with the error that Error getting device API level

### ISSUE THREAD

**Issue by Su-yj** [appium/appium-desktop#1003] opened 2019-06-10 06:02 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The session setting like this:
```json
{
  "platformName": "Android",
  "platformversion": "5.1.1",
  "deviceName": "127.0.0.1:62001",
  "appPackage": "com.tencent.mm",
  "appActivity": "com.tencent.mm.ui.LauncherUI",
  "noReset": true,
  "unicodekeyboard": true,
  "resetkeyboard": true
}
```
and when I start the Session, it raise the error:
```
An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command 'C\:\\SDK\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:62001 shell getprop ro.build.version.sdk' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
```
the log
```
MJSONWP] Calling AppiumDriver.createSession() with args: [{"appActivity":"com.tencent.mm.ui.LauncherUI","appPackage":"com.tencent.mm","deviceName":"127.0.0.1:62001","noReset":true,"platformName":"Android","platformversion":"5.1.1","resetkeyboard":true,"unicodekeyboard":true,"newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1560146508037 (14:01:48 GMT+0800 (中国标准时间))
[Appium] 
[Appium] ======================================================================
[Appium]   DEPRECATION WARNING:
[Appium] 
[Appium]   The 'automationName' capability was not provided in the desired 
[Appium]   capabilities for this Android session
[Appium] 
[Appium]   Setting 'automationName=UiAutomator1' by default and using the 
[Appium]   UiAutomator1 Driver
[Appium] 
[Appium]   The next minor version of Appium (1.14.x) will set 
[Appium]   'automationName=UiAutomator2' by default and use the UiAutomator2 
[Appium]   Driver
[Appium] 
[Appium]   The next major version of Appium (2.x) will **require** the 
[Appium]   'automationName' capability to be set for all sessions on all 
[Appium]   platforms
[Appium] 
[Appium]   If you are happy with 'UiAutomator1' and do not wish to upgrade 
[Appium]   Android drivers, please add 'automationName=UiAutomator1' to your 
[Appium]   desired capabilities
[Appium] 
[Appium]   For more information about drivers, please visit 
[Appium]   http://appium.io/docs/en/about-appium/intro/ and explore the 
[Appium]   'Drivers' menu
[Appium] 
[Appium] ======================================================================
[Appium] 
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Appium v1.13.0 creating new AndroidDriver (v4.15.1) session
[Appium] Capabilities:
[Appium]   appActivity: com.tencent.mm.ui.LauncherUI
[Appium]   appPackage: com.tencent.mm
[Appium]   deviceName: 127.0.0.1:62001
[Appium]   noReset: true
[Appium]   platformName: Android
[Appium]   platformversion: 5.1.1
[Appium]   resetkeyboard: true
[Appium]   unicodekeyboard: true
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[BaseDriver] Creating session with MJSONWP desired capabilities: {"appActivity":"com.tencent...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platformversion, resetkeyboard, unicodekeyboard, connectHardwareKeyboard.
[BaseDriver] Session created with session id: 50a96413-e4e1-479e-99ec-9133975a2a78
[ADB] Using 'adb.exe' from 'C:\SDK\platform-tools\adb.exe'
[AndroidDriver] Retrieving device list
[ADB] Trying to find a connected android device
[ADB] Getting connected devices...
[ADB] 1 device(s) connected
[AndroidDriver] Using device: 127.0.0.1:62001
[ADB] Using 'adb.exe' from 'C:\SDK\platform-tools\adb.exe'
[ADB] Setting device id to 127.0.0.1:62001
[ADB] Running 'C:\SDK\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:62001 shell getprop ro.build.version.sdk'
[AndroidDriver] Shutting down Android driver
[AndroidDriver] Called deleteSession but bootstrap wasn't active
[ADB] Running 'C:\SDK\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:62001 shell am force-stop io.appium.unlock'
[BaseDriver] Event 'newSessionStarted' logged at 1560146515679 (14:01:55 GMT+0800 (中国标准时间))
[MJSONWP] Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command 'C\:\\SDK\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:62001 shell getprop ro.build.version.sdk' exited with code 3221226356'; Stderr: ''; Code: '3221226356'
[MJSONWP]     at ADB. (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\adb-commands.js:98:13)
[MJSONWP]     at Generator.throw ()
[MJSONWP]     at asyncGeneratorStep (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
[MJSONWP]     at _throw (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
[MJSONWP]     at run (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:75:22)
[MJSONWP]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\es6.promise.js:92:30
[MJSONWP]     at flush (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\core-js\modules\_microtask.js:18:9)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)
[HTTP] <-- POST /wd/hub/session 500 7643 ms - 402
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 3 ms - 57
[HTTP] 
```

## Environment

- I am running Appium Desktop version _<1.13.0>_.
- I am on (pick one):
    - [ ] Mac
    - [x] Windows
    - [ ] Linux

**Comment by mykola-mokhnach** [comment] 2019-06-10 06:20
Duplicate of https://github.com/appium/appium/issues/12736

**Closed by mykola-mokhnach** 2019-06-10 06:20 UTC

**Comment by Su-yj** [comment] 2019-06-10 06:47
The Appium is not supper the Android SDK Platform-Tools 29 now, must download the Previous versions less than 29
