### ISSUE TITLE
<parsererror> on musical.ly app

### ISSUE THREAD

**Issue by cozyreal** [appium/appium-desktop#485] opened 2018-04-04 20:10 UTC
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

The inspector doesn't fully show the content of a page in musical.ly (version 6.8.0) app. In the top there is "\<parserror\>\<h3\>\<div\>\<h3\>". To get to the page in the screenshot, open musical.ly, proceed to creating account with phone number and after choosing the birth date, the page will appears (it asks for phone number). I tried to search in the page with xpath //* to see if other elements existed, and in fact there are other elements not showed in the Appium Desktop Inspector
![image](https://user-images.githubusercontent.com/38085109/38331921-e7ad0c38-3854-11e8-9d6d-ada6f2889ee2.png)

## Environment

- I am running Appium Desktop version 1,5,0.
- I am on (pick one):
    - [ ] Mac
    - [X] Windows
    - [ ] Linux

**Comment by dpgraham** [comment] 2018-04-04 21:40
Can you check the Appium server logs?

When you refresh the source/screenshot, it should make a call to `/source` which will show the XML tree. I'd like to know if parseerror shows up in the logs or if it's a UI issue.

**Comment by cozyreal** [comment] 2018-04-05 15:09
Here the log after I click on Refresh button.

`[HTTP] <-- GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/screenshot 200 3370 ms - 291978 
[HTTP] --> GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/source {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/source] to [GET http://localhost:8200/wd/hub/session/2bc2c37a-8c4d-4d56-b3c9-08b2dfcc47e3/source] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"2bc2c37a-8c4d-4d56-b3c9-08b2dfcc47e3\",\"status\":0,\"value\":\"
[JSONWP Proxy] Replacing sessionId 2bc2c37a-8c4d-4d56-b3c9-08b2dfcc47e3 with dbdd7b1f-92c9-481a-802b-18f0c09ec293
[HTTP] <-- GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/source 200 40 ms - 12422 
[HTTP] --> GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["dbdd7b1f-92c9-481a-802b-18f0c09ec293"]
[ADB] Device API level: 23
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABaAAAAoACAYAAABH9IXPAACAAElEQVR4AezBe5Cd52Hf9+/zvO9533Pds7sHCyyw5JIixQikScoQdbElUqItUYrtWBeP77c4Y3niZhIX7X/21P7HGWkcZ1pzJkrqQk2bsai4TmNJjeValmJLJmmZEimLFmWC4g1c4rr3s+f6nvd9n6dFNaig5VnsLrAH2AV+n4/5xeMvekREREREREREREREdphFRERERERERERERGQELCIiIiIiIiIiIiIiI2ARERERERERERERERkBi4iIiIiIiIiIiIjICFhEREREREREREREREbAIiIiIiIiIiIiIiIyAhYRERERERERERERkRGwiIiIiIiIiIiIiIiMgEVEREREREREREREZAQsIiIiIiIiIiIiIiIjYBERERERERERERERGQGLiIiIiIiIiIiIiMgIWERERERERERERERERsAiIiIiIiIiIiIiIjICFhERERERERERERGREbCIiIiIiIiIiIiIiIyARURERERERERERERkBCwiIiIiIiIiIiIiIiMQIryuGFO2lu04NRiwmuWIiIiIiIiIiFyPAmPIvWev+ImpSW4rxlyJJ1odvtpq08kdIrIzQoSf2d/gDaUi2/G/nJnn8bU2IiIiIiIiIrK5fYWQfYWQw6US5cBySxxx3mwxpmwtG+k6x1w/4bxXkgHd3HG812MxzVhMM2Q0ZuOI5SynnefsFbcVY+4ql7gSp5IBTxtLB4eI7IwQkWvMsDmPiIiIiIiI7CWHy0UOl0rcWS4yW4wpW8vlKFvL4XKJ8w6XS3zbBOd1nWOun/Bst8/xXo/j3T5y5WbjiEYhZDnLERG5UiEi11AlsEyGIbUgYCwIKFjDBc571nJHK89ZSjPaeY5HREREREREdqOytbypVuFN1TJ3lkuUrWXUytZyuFzicLkETNB1jme7Pb7W7vK1Voeuc8j2zMYRjUKIiMhOCRG5yqpBwK3FiFvimANRgckwpBxYqtYS...
[HTTP] <-- GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/screenshot 200 3328 ms - 291974 `

**Comment by dpgraham** [comment] 2018-04-05 15:48
Okay so the problem is that source is returning empty object. Which automation are you using. Is this Android?

**Comment by cozyreal** [comment] 2018-04-05 17:19
Yes Android (UiAutomator2). I am using Genymotion as emulator.

**Comment by dpgraham** [comment] 2018-04-05 21:48
@mykola-mokhnach @imurchie At the top of your heads, do you know why `/source` would return empty on Android UiAutomator2?

```
[HTTP] <-- GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/screenshot 200 3370 ms - 291978
[HTTP] --> GET /wd/hub/session/dbdd7b1f-92c9-481a-802b-18f0c09ec293/source {}
```

**Comment by dpgraham** [comment] 2018-04-05 21:49
@cozyreal What version of Android is this and what kind of device is it? Is is it an Emulator or Real Device?

**Comment by mykola-mokhnach** [comment] 2018-04-06 04:57
Due to some internal UIA problem, most likely. Logcat output might tell us more.

**Comment by cozyreal** [comment] 2018-04-06 16:48
@dpgraham I am using Android 6.0.0 on Emulator (Genymotion).
@mykola-mokhnach What do I have to do to get the "Logcat output" you need?

**Comment by cozyreal** [comment] 2018-04-07 08:47
@dpgraham I don't think Genymotion is the problem because UiAutomatorViewer works good and shows me the full source without errors (Appium Inspector instead shows only a part of the source, like if while it's parsing a "parse error" occurs). I'll post the logcat in a few hours.

**Comment by cozyreal** [comment] 2018-04-07 12:24
@dpgraham @mykola-mokhnach Here is the output given by adb logcat when I click on the refresh button in Appium Inspector

04-06 17:18:27.655 16434 16479 I appium  : channel read invoked!
04-06 17:18:27.655 16434 16479 I appium  : channel read: GET /wd/hub/session/bc6a414c-30b2-481c-8dd3-a7847e193e0b/source
04-06 17:18:27.668 16434 16479 I appium  : Skipping invisible child: android.view.accessibility.AccessibilityNodeInfo@80014b26; boundsInParent: Rect(0, 0 - 1440, 0); boundsInScreen: Rect(0, 822 - 1440, 822); packageName: com.zhiliaoapp.musically; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; contentDescription: null; viewIdResName: com.zhiliaoapp.musically:id/a0c; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_UNKNOWN - null]
04-06 17:18:27.668 16434 16479 I appium  : Skipping invisible child: android.view.accessibility.AccessibilityNodeInfo@80015a2a; boundsInParent: Rect(0, 0 - 1440, 0); boundsInScreen: Rect(0, 1537 - 1440, 1537); packageName: com.zhiliaoapp.musically; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; contentDescription: null; viewIdResName: com.zhiliaoapp.musically:id/a0g; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_UNKNOWN - null]
04-06 17:18:27.668 16434 16479 I appium  : Skipping invisible child: android.view.accessibility.AccessibilityNodeInfo@80013c22; boundsInParent: Rect(0, 0 - 1440, 0); boundsInScreen: Rect(0, 2560 - 1440, 2560); packageName: com.zhiliaoapp.musically; className: android.widget.FrameLayout; text: null; error: null; maxTextLength: -1; contentDescription: null; viewIdResName: com.zhiliaoapp.musically:id/a08; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_UNKNOWN - null]
04-06 17:18:27.668 16434 16479 I appium  : Skipping invisible child: android.view.accessibility.AccessibilityNodeInfo@80012d1e; boundsInParent: Rect(0, 0 - 1440, 96); boundsInScreen: Rect(0, 0 - 1440, 96); packageName: com.zhiliaoapp.musically; className: android.view.View; text: null; error: null; maxTextLength: -1; contentDescription: null; viewIdResName: android:id/statusBarBackground; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_UNKNOWN - null]
04-06 17:18:27.669 16434 16479 I appium  : Fetch time: 7ms
04-06 17:18:27.715 16434 16479 I appium  : AppiumResponse: {"sessionId":"bc6a414c-30b2-481c-8dd3-a7847e193e0b","status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><hierarchy rotation=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2560]\" resource-id=\"\" instance=\"0\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2560]\" resource-id=\"\" instance=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,2560]\" resource-id=\"\" instance=\"1\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,2560]\" resource-id=\"com.zhiliaoapp.musically:id\/e6\" instance=\"1\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,2560]\" resource-id=\"android:id\/content\" instance=\"2\"><android.widget.RelativeLayout index=\"0\" text=\"\" class=\"android.widget.RelativeLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,2560]\" resource-id=\"\" instance=\"0\"><android.widget.ScrollView index=\"0\" text=\"\" class=\"android.widget.ScrollView\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,2560]\" resource-id=\"com.zhiliaoapp.musically:id\/a09\" instance=\"0\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,1537]\" resource-id=\"com.zhiliaoapp.musically:id\/a0_\" instance=\"2\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,96][1440,568]\" resource-id=\"com.zhiliaoapp.musically:id\/a0a\" instance=\"3\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.zhiliaoapp.musically\" content-desc=\"\" checkable=\"fal
04-06 17:18:27.882 16482 16482 D         : HostConnection::get() New Host Connection established 0xf661c250, tid 16482
04-06 17:18:27.932   590   590 E EGL_emulation: tid 590: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
04-06 17:18:33.158   541   541 I DeviceStorageMonitorService: No boot image on disk due to lack of space. Sending notification

**Comment by cozyreal** [comment] 2018-04-09 14:03
@dpgraham @mykola-mokhnach news?

**Comment by dpgraham** [comment] 2018-04-09 18:48
@cozyreal I think it's parsing the XML incorrectly. Can you try just running a simple appium script that gets the `/source` (driver.getPageSource() in Java) and then post the XML here?

**Comment by cozyreal** [comment] 2018-04-16 07:52
PS: parsing errors occur also with other pages, where not all the elements are showed, or the parserror is given as in this issue.
@dpgraham @mykola-mokhnach Here the source, anyway:
`<?xml version="1.0" encoding="UTF-8"?><hierarchy rotation="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1440,2560]" resource-id="" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1440,2560]" resource-id="" instance="0"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="" instance="1"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="com.zhiliaoapp.musically:id/e6" instance="1"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="android:id/content" instance="2"><android.widget.RelativeLayout index="0" text="" class="android.widget.RelativeLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="" instance="0"><android.widget.ScrollView index="0" text="" class="android.widget.ScrollView" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="com.zhiliaoapp.musically:id/a09" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,1537]" resource-id="com.zhiliaoapp.musically:id/a0_" instance="2"><android.widget.FrameLayout index="0" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,568]" resource-id="com.zhiliaoapp.musically:id/a0a" instance="3"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,96][1344,568]" resource-id="" instance="3"><android.widget.TextView index="0" text="Inserisci il tuo numero di cellulare" class="android.widget.TextView" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,216][1344,528]" resource-id="com.zhiliaoapp.musically:id/a18" instance="0"/></android.widget.LinearLayout></android.widget.FrameLayout><android.widget.FrameLayout index="1" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,568][1440,822]" resource-id="com.zhiliaoapp.musically:id/a0b" instance="4"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,656][1344,822]" resource-id="" instance="4"><android.widget.RelativeLayout index="0" text="" class="android.widget.RelativeLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,656][480,822]" resource-id="" instance="1"><android.widget.Spinner index="0" text="" class="android.widget.Spinner" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[96,656][460,822]" resource-id="com.zhiliaoapp.musically:id/a0y" instance="0"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,656][460,822]" resource-id="" instance="5"><android.widget.TextView index="0" text="&#55356;&#56826;&#55356;&#56824;+1" class="android.widget.TextView" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,656][388,822]" resource-id="com.zhiliaoapp.musically:id/a1_" instance="1"/></android.widget.LinearLayout></android.widget.Spinner><android.widget.ImageView index="1" text="" class="android.widget.ImageView" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,656][480,800]" resource-id="com.zhiliaoapp.musically:id/a0z" instance="0"/></android.widget.RelativeLayout><android.widget.EditText index="1" text="5555218135" class="android.widget.EditText" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[512,656][1344,822]" resource-id="com.zhiliaoapp.musically:id/a11" instance="0"/></android.widget.LinearLayout></android.widget.FrameLayout><android.widget.FrameLayout index="3" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,822][1440,918]" resource-id="com.zhiliaoapp.musically:id/a0d" instance="5"/><android.widget.FrameLayout index="4" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,918][1440,1345]" resource-id="com.zhiliaoapp.musically:id/a0e" instance="6"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,918][1344,1345]" resource-id="" instance="6"><android.widget.TextView index="0" text="Tocca Avanti per verificare il tuo account con Account Kit di Facebook. Non hai bisogno di un account Facebook per usare Account Kit. Potremmo inviare un SMS per verificare il tuo numero. Potrebbero essere applicati i costi per l'invio di messaggi e la trasmissione dei dati. Scopri com Facebook usa le tue informazioni." class="android.widget.TextView" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="true" password="false" selected="false" bounds="[96,938][1344,1305]" resource-id="com.zhiliaoapp.musically:id/a0r" instance="2"/></android.widget.LinearLayout></android.widget.FrameLayout><android.widget.FrameLayout index="5" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,1345][1440,1537]" resource-id="com.zhiliaoapp.musically:id/a0f" instance="7"><android.widget.LinearLayout index="0" text="" class="android.widget.LinearLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,1345][1344,1537]" resource-id="" instance="7"><android.widget.Button index="0" text="Avanti" class="android.widget.Button" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[96,1345][1344,1537]" resource-id="com.zhiliaoapp.musically:id/a0h" instance="0"/></android.widget.LinearLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.ScrollView></android.widget.RelativeLayout><android.widget.FrameLayout index="1" text="" class="android.widget.FrameLayout" package="com.zhiliaoapp.musically" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,96][1440,2560]" resource-id="com.zhiliaoapp.musically:id/a07" instance="8"/></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></android.widget.LinearLayout></android.widget.FrameLayout></hierarchy>`

**Comment by cozyreal** [comment] 2018-04-28 19:03
@dpgraham @mykola-mokhnach Up

**Comment by dpgraham** [comment] 2018-04-30 16:09
@cozyreal I don't know what the issue is and unfortunately this is probably a pretty low priority fix for us. There's also a 'Search' feature on Appium Desktop that let's you input selectors and test them and apply operations on the searched-for elements.

**Comment by dpgraham** [comment] 2018-10-29 22:52
This is being fixed in https://github.com/appium/appium-desktop/pull/691

Emoji's were breaking XML

**Closed by dpgraham** 2018-10-29 22:52 UTC
Labels: P3
