### ISSUE TITLE
Not map to a valid resource when send keys on windows

### ISSUE THREAD

**Issue by KageyamaRuka** [appium/appium-desktop#1335] opened 2020-04-10 02:43 UTC
## The problem

Not map to a valid resource when send keys script run on windows, but success when run on mac and debian wsl, on windows, it seems ok when just sending chars, but failed when sending file path like string

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Last Appium version that did not exhibit the issue (if applicable): 1.15.1 when script run on mac and debian WSL
* Desktop OS/version used to run Appium: win10 1909
* Node.js version (unless using Appium.app|exe): 12.16.1
* Mobile platform/version under test: windows
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium desktop

## Link to Appium logs

[failed_on_win.log](https://github.com/appium/appium/files/4459570/failed_on_win.log)
[success_on_wsl.log](https://github.com/appium/appium/files/4459571/success_on_wsl.log)
![image](https://user-images.githubusercontent.com/24635872/78957613-67418480-7b18-11ea-9320-d3f592ebcc7f.png)

## Code To Reproduce Issue [ Good To Have ]

https://github.com/KageyamaRuka/issue_demo/blob/master/demo.py

**Comment by KazuCocoa** [comment] 2020-04-10 16:00
Perhaps https://github.com/admc/wd/blob/2759c0680e0c8e5fe4c51f796d0b7925ba49157b/lib/element-commands.js#L47-L70
If the given string existed in the machine, the sendKeys behaves as an upload file.
I assume `D:\\vid.insv` was on the machine.

**Comment by KageyamaRuka** [comment] 2020-04-11 02:03
@KazuCocoa Hi KazuCocoa, in fact, I would like to send a file path to a poped up open-files-window, so the file should be exist on the machine. And it's weird that the script can be run on both mac and linux but not windows, especially considering that the tested software is on windows.

**Comment by KageyamaRuka** [comment] 2020-04-11 02:06
And I think that if sendKeys behaves as an upload file in some cases, uploading file should be a separate operation, not mixed with sendKeys

**Comment by KazuCocoa** [comment] 2020-04-11 03:57
Yeah, the cause is the library's design which used in AppiumDesktop https://github.com/admc/wd

We discussed a bit to move the library to https://github.com/projectxyzio/web2driver or vanilla webdriverio before. (but not yet since we have no much resource for now)

**Comment by KageyamaRuka** [comment] 2020-04-11 04:28
@KazuCocoa thanks for your willing to fix this, by the way, this issue also found with appium python-client, seems like the python-client team should fix it too. Should I open a new ticket there?

**Comment by KazuCocoa** [comment] 2020-04-11 04:43
ah... got it.
Selenium bindings are designed so.
https://github.com/SeleniumHQ/selenium/blob/d3b6ad006bd7dbee59f8539d81cee4f06bd81d64/py/selenium/webdriver/remote/webelement.py#L501-L533
We should add a new API to skip such a file existence check behaviour as Appium bindings.


Does `set_value` work with Python client?
https://github.com/appium/python-client/blob/8779c3d1b0d6fa1d16a34e8883366da523674b36/appium/webdriver/webelement.py#L192
It calls `/session/:sessionId/element/:id/value` which is supported by WAD. It could be an alternative

**Comment by KageyamaRuka** [comment] 2020-04-11 06:36
@KazuCocoa I'm afraid `set_value` doesn't work, which raise an exception that `Command not recognized`. Here is the log:
[set-value-logs.txt](https://github.com/appium/appium-desktop/files/4464150/set-value-logs.txt)

**Comment by KazuCocoa** [comment] 2020-04-11 07:45
Sorry, the path of python client was my wrong.

Could you apply the below PR change in your local? And try to call the method if it works well?
https://github.com/appium/python-client/pull/515

**Comment by KageyamaRuka** [comment] 2020-04-11 08:24
@KazuCocoa the `send_keys_direct` without `is_local_file` check can send file path string properly now, good job!

**Comment by KazuCocoa** [comment] 2020-04-11 10:35
okay. Let me consider the behavour more. Will notify you when I finish the PR.

**Comment by KazuCocoa** [comment] 2020-04-12 03:27
The `element.send_keys` behaves as same as `send_keys_direct` with Python client 0.51

**Comment by KazuCocoa** [comment] 2020-04-19 03:18
Close this issue so far.
The root cause is appium client's implementation

**Closed by KazuCocoa** 2020-04-19 03:18 UTC
Labels: enhancement
