### ISSUE TITLE
can not get the value of XCUIElementTypeOther on iOS 12.6 with Appium1.15.1

### ISSUE THREAD

**Issue by qinlizql** [appium/appium-desktop#1199] opened 2019-12-13 06:01 UTC
After upgrade Appium from 1.14 to 1.15.1, can not get the value of XCUIElementTypeOther on iOS 12.6

Environment:
1.  Xcode11.3
2. Appium-Deskptop 1.15.1
3. iOS version: 12.6
4. Language: Python

Code as below:
txt_country = (MobileBy.XPATH,
                   '//XCUIElementTypeStaticText[@name="Mobile Number or Email"]/../preceding-sibling::XCUIElementTypeOther[1]')

 elements = self.driver.find_elements(txt_country)
if len(elements)>0:
       value = elements.__getitem__(0).text

In this code, the parameter value show as '', but the code works on ios13.
Also checked with page source, it displayed there.
But in debug window, checked the object property, see it text property show as ''.

Does any one get similar issue and has solutions on this?

**Comment by KazuCocoa** [comment] 2019-12-13 15:30
Did you try Xcode 10 for the environment?

Xcode 11 and non-iOS 13 have issues in XCTest framework layer
https://github.com/appium/appium/issues/13288

**Comment by deepakarorawins** [comment] 2019-12-20 12:47
Hi Friends,
Did we get any workaround?
I wonder how others are surviving with this!

**Comment by qinlizql** [comment] 2019-12-24 08:59
> Hi Friends,
> Did we get any workaround?
> I wonder how others are surviving with this!

Solve the issue by get page source. When you go through the page source, you will find the object and it's value presents there.
Just go though the page source and get the words you wanted.

**Comment by qinlizql** [comment] 2019-12-24 09:00
> Did you try Xcode 10 for the environment?
> 
> Xcode 11 and non-iOS 13 have issues in XCTest framework layer
> [appium/appium#13288](https://github.com/appium/appium/issues/13288)

I don't think it's xcode11 issue. 
When using xcode11 and appium1.14, no this issue.

**Comment by KazuCocoa** [comment] 2019-12-24 10:22
Ah.. interesting.
We changed an API to get elements from deprecated one to another one for iOS 13 support in 1.15.0. Appium decided which API should use with 'selector'. Potentially, it could be relevant I guess. but we cannot remove the logic since cannot drop iOS 13 support. (Then, XCTest also has the same issue, I assume)

Source command gets elements recursively. So, if it can get with the command, maybe the value exists around the element...

How about 1.16.0, BTW?

**Comment by deepakarorawins** [comment] 2020-01-01 03:12
No luck with Appium 1.16.0 and ios 12.4 real device also; couldn't get a chance to check with other ios versions.

**Comment by stone20130104** [comment] 2020-01-07 07:15
This same issue happens on XCUIElementTypeTextField too. Here is the example, the original value of XCUIElementTypeTextField is "aaa", when i do send_keys("bbb") on this XCUIElementTypeTextField, and then get value of this XCUIElementTypeTextField, the value is still "aaa", seems it is not updated accordingly. 
This happens only after Appium upgraded to Appium-Deskptop 1.15.1.
Environment:
Xcode11.1
Appium-Deskptop 1.15.1
iOS version: 11.3 
Language: Python

**Comment by qinlizql** [comment] 2020-01-10 08:28
> This same issue happens on XCUIElementTypeTextField too. Here is the example, the original value of XCUIElementTypeTextField is "aaa", when i do send_keys("bbb") on this XCUIElementTypeTextField, and then get value of this XCUIElementTypeTextField, the value is still "aaa", seems it is not updated accordingly.
> This happens only after Appium upgraded to Appium-Deskptop 1.15.1.
> Environment:
> Xcode11.1
> Appium-Deskptop 1.15.1
> iOS version: 11.3
> Language: Python

Did you try after page refresh? It should work.

**Comment by LexXia-1** [comment] 2020-03-04 05:52
Environment:


Appium-Deskptop 1.15.1
iOS version: 12.2
Language: Java
When I do clear() ,it doesn't take effect

**Comment by KazuCocoa** [comment] 2020-06-20 06:44
> When using xcode11 and appium1.14, no this issue.

For more note about https://github.com/appium/appium-desktop/issues/1199#issuecomment-568716821

The diff may be relative to this behaviour change is below.
Apple started printing deprecation warning for `_XCT_snapshotForElement` from Xcode 11, so we started using `_XCT_requestSnapshotForElement` instead following Xcode. Appium refered `_XCT_requestSnapshotForElement` first if the method was available with _selector_.

Potentially, the `_XCT_requestSnapshotForElement` had an issue to find elements, but Apple deprecated `_XCT_snapshotForElement` so as Appium, we cannot use the method first for newser Xcode versions.

If you have a change, you can make 
https://github.com/appium/WebDriverAgent/blob/a44bb179a74e3bf29516e8b72a1fdbe801b9da30/WebDriverAgentLib/Utilities/FBXCodeCompatibility.m#L182 return `true` every time. Then, WDA referees to `_XCT_snapshotForElement` forcefully.
If the case works well, the root issue is in `_XCT_requestSnapshotForElement` (Apple side)

---

Close this issue for now since my current assumption is API by Xcode as the above.
It is appreciated if someone can try the above comment to clarify the cause. (And figure out the cause..)

**Closed by KazuCocoa** 2020-06-20 06:44 UTC
